
  export const PlanningApps = [
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SY3PC6EWJRR00&activeTab=summary",
    "address": "1F2 76 Grassmarket Old Town Edinburgh EH1 2JR",
    "postcode": "EH1 2JR",
    "received": "Received: Thu 19 Jun 2025",
    "validated": "Validated: Thu 19 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.947832",
    "longitude": "-3.195535",
    "reference": "Ref. No: 25/03210/CLESTL",
    "title": "Operation of a short term let for over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SY05JWEWJGU00&activeTab=summary",
    "address": "Flat 7 15 Tron Square Old Town Edinburgh EH1 1RT",
    "postcode": "EH1 1RT",
    "received": "Received: Tue 17 Jun 2025",
    "validated": "Validated: Tue 17 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949367",
    "longitude": "-3.188808",
    "reference": "Ref. No: 25/03172/CLESTL",
    "title": "Short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXSA7PEWIZ400&activeTab=summary",
    "address": "1F1 16 Broughton Place Broughton Edinburgh EH1 3RX",
    "postcode": "EH1 3RX",
    "received": "Received: Fri 13 Jun 2025",
    "validated": "Validated: Thu 19 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958794",
    "longitude": "-3.189066",
    "reference": "Ref. No: 25/03091/CLESTL",
    "title": "The property has been operating continuously as a short term let since hosting the first guest on 7th March 2014."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXOKVNEWILB00&activeTab=summary",
    "address": "1F1 62 Thistle Street New Town Edinburgh EH2 1EN",
    "postcode": "EH2 1EN",
    "received": "Received: Wed 11 Jun 2025",
    "validated": "Validated: Wed 11 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953847",
    "longitude": "-3.199387",
    "reference": "Ref. No: 25/03032/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXOKVWEWILK00&activeTab=summary",
    "address": "Flat 3 5 Hopetoun Crescent Broughton Edinburgh EH7 4AY",
    "postcode": "EH7 4AY",
    "received": "Received: Wed 11 Jun 2025",
    "validated": "Validated: Wed 11 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.961421",
    "longitude": "-3.184532",
    "reference": "Ref. No: 25/03035/CLESTL",
    "title": "Application for Certificate of Lawful use of short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXN6WEEWIJ300&activeTab=summary",
    "address": "40 Polwarth Crescent Polwarth Edinburgh EH11 1HN",
    "postcode": "EH11 1HN",
    "received": "Received: Tue 10 Jun 2025",
    "validated": "Validated: Tue 10 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938096",
    "longitude": "-3.217583",
    "reference": "Ref. No: 25/03028/FULSTL",
    "title": "Change of use to short term let accommodation (in retrospect) for up to 3 months (June-August) of each calendar year."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXLC75EWICG00&activeTab=summary",
    "address": "11 St Stephen Place Edinburgh EH3 5AJ",
    "postcode": "EH3 5AJ",
    "received": "Received: Mon 09 Jun 2025",
    "validated": "Validated: Mon 09 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958112",
    "longitude": "-3.207079",
    "reference": "Ref. No: 25/03001/FULSTL",
    "title": "Change of use from residential basement flat to short term let (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXK0YXEWI7C00&activeTab=summary",
    "address": "Flat 7 21B Brunswick Road Edinburgh EH7 5FN",
    "postcode": "EH7 5FN",
    "received": "Received: Sun 08 Jun 2025",
    "validated": "Validated: Mon 16 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960179",
    "longitude": "-3.17764",
    "reference": "Ref. No: 25/02986/FULSTL",
    "title": "Change of use from residential flat (sui generis) to short term let (sui generis)"
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXK0W9EWI6J00&activeTab=summary",
    "address": "Flat 10 127 Lothian Road Edinburgh EH3 9AD",
    "postcode": "EH3 9AD",
    "received": "Received: Sun 08 Jun 2025",
    "validated": "Validated: Sun 08 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94561",
    "longitude": "-3.205042",
    "reference": "Ref. No: 25/02977/FULSTL",
    "title": "Change of use from residential flat (sui generis) to short term let (sui generis) in retrospect."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXK0W4EWI6B00&activeTab=summary",
    "address": "Flat 4 4 Carrubber's Close 135 High Street Edinburgh EH1 1SJ",
    "postcode": "EH1 1SJ",
    "received": "Received: Sun 08 Jun 2025",
    "validated": "Validated: Sun 08 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950669",
    "longitude": "-3.187022",
    "reference": "Ref. No: 25/02975/CLESTL",
    "title": "Short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXK0VZEWI6400&activeTab=summary",
    "address": "Flat 3 160B Canongate Edinburgh EH8 8DD",
    "postcode": "EH8 8DD",
    "received": "Received: Sun 08 Jun 2025",
    "validated": "Validated: Sun 08 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951465",
    "longitude": "-3.178943",
    "reference": "Ref. No: 25/02974/CLESTL",
    "title": "Use of flat as short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXFL9QEWI2Y00&activeTab=summary",
    "address": "1F 6 St Mary's Street Old Town Edinburgh EH1 1SU",
    "postcode": "EH1 1SU",
    "received": "Received: Fri 06 Jun 2025",
    "validated": "Validated: Fri 06 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950369",
    "longitude": "-3.183618",
    "reference": "Ref. No: 25/02961/FULSTL",
    "title": "Change of use from residential flat to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXFLA1EWI3400&activeTab=summary",
    "address": "3F 6 St Mary's Street Old Town Edinburgh EH1 1SU",
    "postcode": "EH1 1SU",
    "received": "Received: Fri 06 Jun 2025",
    "validated": "Validated: Fri 06 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950369",
    "longitude": "-3.183618",
    "reference": "Ref. No: 25/02963/FULSTL",
    "title": "Change of use from residential flat to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXFS7PEWI3Y00&activeTab=summary",
    "address": "21A Queen Street New Town Edinburgh EH2 1JX",
    "postcode": "EH2 1JX",
    "received": "Received: Fri 06 Jun 2025",
    "validated": "Validated: Fri 06 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954483",
    "longitude": "-3.199583",
    "reference": "Ref. No: 25/02967/FULSTL",
    "title": "Change of use (retrospective) from residential to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXFL9UEWI3100&activeTab=summary",
    "address": "2F 6 St Mary's Street Old Town Edinburgh EH1 1SU",
    "postcode": "EH1 1SU",
    "received": "Received: Fri 06 Jun 2025",
    "validated": "Validated: Fri 06 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950369",
    "longitude": "-3.183618",
    "reference": "Ref. No: 25/02962/FULSTL",
    "title": "Change of use from residential flat to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXDXIUEWHYH00&activeTab=summary",
    "address": "25 Cheyne Street Stockbridge Edinburgh EH4 1JD",
    "postcode": "EH4 1JD",
    "received": "Received: Thu 05 Jun 2025",
    "validated": "Validated: Tue 10 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958734",
    "longitude": "-3.212769",
    "reference": "Ref. No: 25/02946/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXC2XMEWHQP00&activeTab=summary",
    "address": "Unit 6 219 High Street Edinburgh EH1 1PE",
    "postcode": "EH1 1PE",
    "received": "Received: Wed 04 Jun 2025",
    "validated": "Validated: Wed 04 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950169",
    "longitude": "-3.189026",
    "reference": "Ref. No: 25/02919/FULSTL",
    "title": "Change of use (retrospective) from residential to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXC2XWEWHQV00&activeTab=summary",
    "address": "Unit 7 219 High Street Edinburgh EH1 1PE",
    "postcode": "EH1 1PE",
    "received": "Received: Wed 04 Jun 2025",
    "validated": "Validated: Wed 04 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950169",
    "longitude": "-3.189026",
    "reference": "Ref. No: 25/02921/FULSTL",
    "title": "Change of use (retrospective) from residential to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SXC2XGEWHQM00&activeTab=summary",
    "address": "GF 33 St Bernard's Crescent Edinburgh EH4 1NR",
    "postcode": "EH4 1NR",
    "received": "Received: Wed 04 Jun 2025",
    "validated": "Validated: Thu 05 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957751",
    "longitude": "-3.213091",
    "reference": "Ref. No: 25/02918/FULSTL",
    "title": "Change of use (retrospective) from residential to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SX9RKUEWHEL00&activeTab=summary",
    "address": "9 Forrest Road Edinburgh EH1 2QH",
    "postcode": "EH1 2QH",
    "received": "Received: Tue 03 Jun 2025",
    "validated": "Validated: Tue 03 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946261",
    "longitude": "-3.19129",
    "reference": "Ref. No: 25/02878/FULSTL",
    "title": "Change of Use from Offices to 4 Units Short Term Lets studio apartments (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SX7WVKEWH7Z00&activeTab=summary",
    "address": "BF 15 Lynedoch Place Edinburgh EH3 7PY",
    "postcode": "EH3 7PY",
    "received": "Received: Mon 02 Jun 2025",
    "validated": "Validated: Mon 02 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952041",
    "longitude": "-3.21493",
    "reference": "Ref. No: 25/02855/FULSTL",
    "title": "Change of use of basement flat to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SX2CXOEWH1000&activeTab=summary",
    "address": "3F2 112A West Bow Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "received": "Received: Fri 30 May 2025",
    "validated": "Validated: Wed 04 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948217",
    "longitude": "-3.194297",
    "reference": "Ref. No: 25/02834/FULSTL",
    "title": "Retrospective Change of Use from residential flat to Short Term Let (STL) (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SX0I7JEWGTB00&activeTab=summary",
    "address": "4F 15 James' Court 493 Lawnmarket Edinburgh EH1 2PB",
    "postcode": "EH1 2PB",
    "received": "Received: Thu 29 May 2025",
    "validated": "Validated: Tue 03 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949401",
    "longitude": "-3.194062",
    "reference": "Ref. No: 25/02797/FULSTL",
    "title": "Change of Use application for Short term Let as used for 7 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SX0I7MEWGTE00&activeTab=summary",
    "address": "Flat 5 20 Timber Bush North Leith Edinburgh EH6 6QH",
    "postcode": "EH6 6QH",
    "received": "Received: Thu 29 May 2025",
    "validated": "Validated: Thu 29 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.976553",
    "longitude": "-3.167881",
    "reference": "Ref. No: 25/02798/CLESTL",
    "title": "Short Term Let use."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWX2NBEWGGA00&activeTab=summary",
    "address": "16A Canning Street Edinburgh EH3 8EG",
    "postcode": "EH3 8EG",
    "received": "Received: Tue 27 May 2025",
    "validated": "Validated: Tue 27 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94795",
    "longitude": "-3.210175",
    "reference": "Ref. No: 25/02764/FULSTL",
    "title": "Change of use of former offices (class 4) to short term lets (sui-generis) and changing existing windows to new doors and changes to existing window openings."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWUY93EWG8S00&activeTab=summary",
    "address": "13 Teviotdale Place Stockbridge Edinburgh EH3 5HY",
    "postcode": "EH3 5HY",
    "received": "Received: Mon 26 May 2025",
    "validated": "Validated: Mon 16 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.961714",
    "longitude": "-3.208088",
    "reference": "Ref. No: 25/02736/FULSTL",
    "title": "Change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWLYOTEWFMW00&activeTab=summary",
    "address": "35 Blair Street Edinburgh EH1 1QR",
    "postcode": "EH1 1QR",
    "received": "Received: Wed 21 May 2025",
    "validated": "Validated: Mon 26 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949098",
    "longitude": "-3.187758",
    "reference": "Ref. No: 25/02626/FULSTL",
    "title": "Change of use from basement residential flat to short term let (STL) (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWJU7QEWN3600&activeTab=summary",
    "address": "Flat 4 123 Bellevue Road Edinburgh EH7 4DG",
    "postcode": "EH7 4DG",
    "received": "Received: Tue 20 May 2025",
    "validated": "Validated: Mon 26 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.964188",
    "longitude": "-3.188333",
    "reference": "Ref. No: 25/02592/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWJU8REWN3Y00&activeTab=summary",
    "address": "4 Blackie House Wardrop's Court Edinburgh EH1 2NY",
    "postcode": "EH1 2NY",
    "received": "Received: Tue 20 May 2025",
    "validated": "Validated: Tue 20 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949906",
    "longitude": "-3.193404",
    "reference": "Ref. No: 25/02600/CLESTL",
    "title": "Use of flat for short term let use."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWIG95EWN1E00&activeTab=summary",
    "address": "Flat 61 89 Holyrood Road Edinburgh EH8 8BA",
    "postcode": "EH8 8BA",
    "received": "Received: Mon 19 May 2025",
    "validated": "Validated: Mon 19 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951199",
    "longitude": "-3.176725",
    "reference": "Ref. No: 25/02589/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWIG8XEWN1B00&activeTab=summary",
    "address": "31 Barony Street Edinburgh EH3 6PD",
    "postcode": "EH3 6PD",
    "received": "Received: Mon 19 May 2025",
    "validated": "Validated: Wed 21 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957985",
    "longitude": "-3.190513",
    "reference": "Ref. No: 25/02588/FULSTL",
    "title": "Change of use from residential flat (Sui Generis) to short term let accommodation (Sui Generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWIG9CEWN1H00&activeTab=summary",
    "address": "Flat 1B 1 World's End Close Edinburgh EH1 1TD",
    "postcode": "EH1 1TD",
    "received": "Received: Mon 19 May 2025",
    "validated": "Validated: Wed 21 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950374",
    "longitude": "-3.1845",
    "reference": "Ref. No: 25/02590/FULSTL",
    "title": "Retrospective change of use of hostel to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWCPCCEWMMH00&activeTab=summary",
    "address": "Flat 42 12 Pilrig Heights Pilrig Edinburgh EH6 5BB",
    "postcode": "EH6 5BB",
    "received": "Received: Fri 16 May 2025",
    "validated": "Validated: Fri 16 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.966309",
    "longitude": "-3.185482",
    "reference": "Ref. No: 25/02548/FULSTL",
    "title": "Retrospective change of use from residential Flat (Sui Generis) to short term let holiday accommodation (Sui Generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWCFL8EWMK600&activeTab=summary",
    "address": "18 Glen Street Tollcross Edinburgh EH3 9JF",
    "postcode": "EH3 9JF",
    "received": "Received: Fri 16 May 2025",
    "validated": "Validated: Mon 19 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.943902",
    "longitude": "-3.201962",
    "reference": "Ref. No: 25/02540/FULSTL",
    "title": "Retrospective change of use from small flat to short term let visitor accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWAKWTEWMCJ00&activeTab=summary",
    "address": "2F3 24 Dundonald Street Edinburgh EH3 6RY",
    "postcode": "EH3 6RY",
    "received": "Received: Thu 15 May 2025",
    "validated": "Validated: Tue 20 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959332",
    "longitude": "-3.196643",
    "reference": "Ref. No: 25/02505/FULSTL",
    "title": "Retrospective change of use of residential flat to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SWAKWVEWMCM00&activeTab=summary",
    "address": "1F4 3 South Lorne Place Edinburgh EH6 8QN",
    "postcode": "EH6 8QN",
    "received": "Received: Thu 15 May 2025",
    "validated": "Validated: Tue 20 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.966548",
    "longitude": "-3.172785",
    "reference": "Ref. No: 25/02506/FULSTL",
    "title": "Retrospective change of use from residential to short term let holiday accommodation (Sui Generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW96VIEWM9B00&activeTab=summary",
    "address": "89 Brunswick Street Hillside Edinburgh EH7 5HS",
    "postcode": "EH7 5HS",
    "received": "Received: Wed 14 May 2025",
    "validated": "Validated: Mon 16 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960374",
    "longitude": "-3.180351",
    "reference": "Ref. No: 25/02491/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW8Q92EWM6700&activeTab=summary",
    "address": "1 Alva Place Edinburgh EH7 5AZ",
    "postcode": "EH7 5AZ",
    "received": "Received: Wed 14 May 2025",
    "validated": "Validated: Fri 23 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958191",
    "longitude": "-3.169985",
    "reference": "Ref. No: 25/02482/FULSTL",
    "title": "Retrospective change of use of residential flat to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW96VUEWM9F00&activeTab=summary",
    "address": "Flat 1 2 Edmonstone's Close Edinburgh EH1 2HB",
    "postcode": "EH1 2HB",
    "received": "Received: Wed 14 May 2025",
    "validated": "Validated: Wed 14 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948108",
    "longitude": "-3.194007",
    "reference": "Ref. No: 25/02492/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW6VKJEWLWX00&activeTab=summary",
    "address": "3F4 9 Holyrood Road Edinburgh EH8 8AE",
    "postcode": "EH8 8AE",
    "received": "Received: Tue 13 May 2025",
    "validated": "Validated: Tue 13 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949407",
    "longitude": "-3.18274",
    "reference": "Ref. No: 25/02437/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW7C8EEWM2G00&activeTab=summary",
    "address": "20 Fraser Avenue Edinburgh EH5 2AE",
    "postcode": "EH5 2AE",
    "received": "Received: Tue 13 May 2025",
    "validated": "Validated: Wed 28 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.972913",
    "longitude": "-3.216001",
    "reference": "Ref. No: 25/02466/FULSTL",
    "title": "Change of use from residential flat, (sui generis), to short term let property, (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW6VK8EWLWR00&activeTab=summary",
    "address": "2F2 67 Brunswick Street Edinburgh EH7 5HT",
    "postcode": "EH7 5HT",
    "received": "Received: Tue 13 May 2025",
    "validated": "Validated: Tue 13 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959918",
    "longitude": "-3.180113",
    "reference": "Ref. No: 25/02435/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW6VL9EWLXF00&activeTab=summary",
    "address": "21A Stafford Street Edinburgh EH3 7BJ",
    "postcode": "EH3 7BJ",
    "received": "Received: Tue 13 May 2025",
    "validated": "Validated: Tue 13 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950146",
    "longitude": "-3.211636",
    "reference": "Ref. No: 25/02441/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW50W3EWLPM00&activeTab=summary",
    "address": "Flat 5 7 St Mary's Street Edinburgh EH1 1TA",
    "postcode": "EH1 1TA",
    "received": "Received: Mon 12 May 2025",
    "validated": "Validated: Tue 13 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950309",
    "longitude": "-3.184224",
    "reference": "Ref. No: 25/02406/FULSTL",
    "title": "Change flat from long term to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW5HLKEWLUD00&activeTab=summary",
    "address": "2F3 29 Lauriston Street Edinburgh EH3 9DQ",
    "postcode": "EH3 9DQ",
    "received": "Received: Mon 12 May 2025",
    "validated": "Validated: Mon 12 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.945288",
    "longitude": "-3.200756",
    "reference": "Ref. No: 25/02429/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SW5HJYEWLTT00&activeTab=summary",
    "address": "1F 1 St Bernard's Crescent Edinburgh EH4 1NR",
    "postcode": "EH4 1NR",
    "received": "Received: Mon 12 May 2025",
    "validated": "Validated: Thu 15 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957751",
    "longitude": "-3.213091",
    "reference": "Ref. No: 25/02423/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVZGWVEWLJC00&activeTab=summary",
    "address": "3F1 5 Spittal Street Edinburgh EH3 9DY",
    "postcode": "EH3 9DY",
    "received": "Received: Fri 09 May 2025",
    "validated": "Validated: Mon 12 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946131",
    "longitude": "-3.203712",
    "reference": "Ref. No: 25/02390/CLESTL",
    "title": "Continued use as short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVXM8KEWLB400&activeTab=summary",
    "address": "Flat 1 19 Caledonian Crescent Edinburgh EH11 2AL",
    "postcode": "EH11 2AL",
    "received": "Received: Thu 08 May 2025",
    "validated": "Validated: Thu 05 Jun 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942639",
    "longitude": "-3.217117",
    "reference": "Ref. No: 25/02366/CLESTL",
    "title": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVVRJ2EWL2P00&activeTab=summary",
    "address": "3F3 112A West Bow Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "received": "Received: Wed 07 May 2025",
    "validated": "Validated: Wed 14 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948217",
    "longitude": "-3.194297",
    "reference": "Ref. No: 25/02334/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVVRIXEWL2J00&activeTab=summary",
    "address": "2F3 22 William Street Edinburgh EH3 7NH",
    "postcode": "EH3 7NH",
    "received": "Received: Wed 07 May 2025",
    "validated": "Validated: Mon 12 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94942",
    "longitude": "-3.211965",
    "reference": "Ref. No: 25/02332/CLESTL",
    "title": "Continued use as a short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVW1CZEWL6A00&activeTab=summary",
    "address": "Flat 2 65 Caledonian Crescent Edinburgh EH11 2AT",
    "postcode": "EH11 2AT",
    "received": "Received: Wed 07 May 2025",
    "validated": "Validated: Wed 07 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.941956",
    "longitude": "-3.218921",
    "reference": "Ref. No: 25/02353/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVW1D4EWL6D00&activeTab=summary",
    "address": "Flat 1 65 Caledonian Crescent Edinburgh EH11 2AT",
    "postcode": "EH11 2AT",
    "received": "Received: Wed 07 May 2025",
    "validated": "Validated: Wed 07 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.941956",
    "longitude": "-3.218921",
    "reference": "Ref. No: 25/02354/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVU6NWEWKYC00&activeTab=summary",
    "address": "Flat 6 9 Cables Wynd North Leith Edinburgh EH6 6DU",
    "postcode": "EH6 6DU",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.973497",
    "longitude": "-3.175206",
    "reference": "Ref. No: 25/02319/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVU6NQEWKY300&activeTab=summary",
    "address": "2F1 2 West Norton Place Abbeyhill Edinburgh EH7 5AW",
    "postcode": "EH7 5AW",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957284",
    "longitude": "-3.171848",
    "reference": "Ref. No: 25/02316/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVU6NGEWKXU00&activeTab=summary",
    "address": "6 Abbey Mount Abbeyhill Edinburgh EH8 8EJ",
    "postcode": "EH8 8EJ",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95629",
    "longitude": "-3.171852",
    "reference": "Ref. No: 25/02313/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVUDJREWKZM00&activeTab=summary",
    "address": "Flat 6 42 Shore Edinburgh EH6 6QU",
    "postcode": "EH6 6QU",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.975806",
    "longitude": "-3.16954",
    "reference": "Ref. No: 25/02325/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVTWUWEWKW400&activeTab=summary",
    "address": "6 Parkside Street Edinburgh EH8 9RL",
    "postcode": "EH8 9RL",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Thu 08 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.941761",
    "longitude": "-3.178039",
    "reference": "Ref. No: 25/02307/CLESTL",
    "title": "To confirm use of the property as a short term let and office space does not amount to a material change of use."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVUDK6EWKZV00&activeTab=summary",
    "address": "1F1 3 West Norton Place Abbeyhill Edinburgh EH7 5AW",
    "postcode": "EH7 5AW",
    "received": "Received: Tue 06 May 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957284",
    "longitude": "-3.171848",
    "reference": "Ref. No: 25/02327/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVKNK0EWKH900&activeTab=summary",
    "address": "Flat 1 1 Castle Wynd South Old Town Edinburgh EH1 2JT",
    "postcode": "EH1 2JT",
    "received": "Received: Thu 01 May 2025",
    "validated": "Validated: Thu 01 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.947781",
    "longitude": "-3.196653",
    "reference": "Ref. No: 25/02247/CLESTL",
    "title": "Use of flat as short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ2QTEWKCS00&activeTab=summary",
    "address": "Flat 2 4 Old Assembly Close 172 High Street Edinburgh EH1 1QX",
    "postcode": "EH1 1QX",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Tue 06 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949729",
    "longitude": "-3.189411",
    "reference": "Ref. No: 25/02224/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ9K8EWKE800&activeTab=summary",
    "address": "30 Oxgangs Crescent Firrhill Edinburgh EH13 9HL",
    "postcode": "EH13 9HL",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.910755",
    "longitude": "-3.221989",
    "reference": "Ref. No: 25/02233/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ9JUEWKE200&activeTab=summary",
    "address": "Flat 1 6 Tytler Gardens Abbeyhill Edinburgh EH8 8HQ",
    "postcode": "EH8 8HQ",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954672",
    "longitude": "-3.169591",
    "reference": "Ref. No: 25/02231/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ9JFEWKDZ00&activeTab=summary",
    "address": "Flat 4 20 Lochrin Place Tollcross Edinburgh EH3 9QS",
    "postcode": "EH3 9QS",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942558",
    "longitude": "-3.205234",
    "reference": "Ref. No: 25/02230/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ2R2EWKCV00&activeTab=summary",
    "address": "1F2 19 Royal Park Terrace Edinburgh EH8 8JB",
    "postcode": "EH8 8JB",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954837",
    "longitude": "-3.159794",
    "reference": "Ref. No: 25/02225/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ2R9EWKCY00&activeTab=summary",
    "address": "Flat 2 20 Lochrin Place Tollcross Edinburgh EH3 9QS",
    "postcode": "EH3 9QS",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942558",
    "longitude": "-3.205234",
    "reference": "Ref. No: 25/02226/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVJ2RIEWKD100&activeTab=summary",
    "address": "Flat 2 24 Lochrin Place Tollcross Edinburgh EH3 9QS",
    "postcode": "EH3 9QS",
    "received": "Received: Wed 30 Apr 2025",
    "validated": "Validated: Wed 30 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942558",
    "longitude": "-3.205234",
    "reference": "Ref. No: 25/02227/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SVGY7AEWK1500&activeTab=summary",
    "address": "3F1 37 Milton Street Abbeyhill Edinburgh EH8 8HB",
    "postcode": "EH8 8HB",
    "received": "Received: Tue 29 Apr 2025",
    "validated": "Validated: Tue 29 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953945",
    "longitude": "-3.168592",
    "reference": "Ref. No: 25/02171/CLESTL",
    "title": "Short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV7OW1EWJHW00&activeTab=summary",
    "address": "Flat 23 89 Holyrood Road Edinburgh EH8 8BA",
    "postcode": "EH8 8BA",
    "received": "Received: Thu 24 Apr 2025",
    "validated": "Validated: Thu 24 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951199",
    "longitude": "-3.176725",
    "reference": "Ref. No: 25/02103/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV7OW5EWJI100&activeTab=summary",
    "address": "Flat 12 200 Great Junction Street Edinburgh EH6 5LW",
    "postcode": "EH6 5LW",
    "received": "Received: Thu 24 Apr 2025",
    "validated": "Validated: Thu 24 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.974706",
    "longitude": "-3.177889",
    "reference": "Ref. No: 25/02104/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV640FEWJED00&activeTab=summary",
    "address": "11 Tinto Place Bonnington Edinburgh EH6 5GD",
    "postcode": "EH6 5GD",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.97051",
    "longitude": "-3.183529",
    "reference": "Ref. No: 25/02092/FULSTL",
    "title": "Change of use from Class 4 (office) to 2 x short term let (sui generis) accommodation units, with external alterations."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV640DEWJEA00&activeTab=summary",
    "address": "6 Almond Bank Cottages Cramond Edinburgh EH4 6PJ",
    "postcode": "EH4 6PJ",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.975054",
    "longitude": "-3.301895",
    "reference": "Ref. No: 25/02091/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV63ZREWJDW00&activeTab=summary",
    "address": "1F1 100 West Bow Old Town Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948217",
    "longitude": "-3.194297",
    "reference": "Ref. No: 25/02089/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV63ZIEWJDQ00&activeTab=summary",
    "address": "1 Rosebank Cottages Edinburgh EH3 8DA",
    "postcode": "EH3 8DA",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.944973",
    "longitude": "-3.21093",
    "reference": "Ref. No: 25/02087/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV63Z5EWJDJ00&activeTab=summary",
    "address": "Flat 2 84 Spring Gardens Abbeyhill Edinburgh EH8 8HX",
    "postcode": "EH8 8HX",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954905",
    "longitude": "-3.164953",
    "reference": "Ref. No: 25/02086/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV63Z2EWJDG00&activeTab=summary",
    "address": "Flat 4 43 New Street Edinburgh EH8 8BH",
    "postcode": "EH8 8BH",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951085",
    "longitude": "-3.182504",
    "reference": "Ref. No: 25/02085/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV63YWEWJDA00&activeTab=summary",
    "address": "4F1 7 Johnston Terrace Edinburgh EH1 2PW",
    "postcode": "EH1 2PW",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Mon 28 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948508",
    "longitude": "-3.194914",
    "reference": "Ref. No: 25/02083/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV6AW1EWJFV00&activeTab=summary",
    "address": "5 Kirk Street Pilrig Edinburgh EH6 5EX",
    "postcode": "EH6 5EX",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.970583",
    "longitude": "-3.173676",
    "reference": "Ref. No: 25/02100/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV640KEWJEG00&activeTab=summary",
    "address": "103 Webster's Land Tollcross Edinburgh EH1 2RU",
    "postcode": "EH1 2RU",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946598",
    "longitude": "-3.199548",
    "reference": "Ref. No: 25/02093/CLESTL",
    "title": "Use as short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV6AW4EWJG000&activeTab=summary",
    "address": "Flat 1 11 Hart Street Broughton Edinburgh EH1 3RN",
    "postcode": "EH1 3RN",
    "received": "Received: Wed 23 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958428",
    "longitude": "-3.187917",
    "reference": "Ref. No: 25/02101/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV4G8IEWJ8900&activeTab=summary",
    "address": "2F3 112A West Bow Old Town Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "received": "Received: Tue 22 Apr 2025",
    "validated": "Validated: Tue 22 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948217",
    "longitude": "-3.194297",
    "reference": "Ref. No: 25/02072/FULSTL",
    "title": "Change of use from smalll flat to short term let (STL) (sui generis in retrospect)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SV3ZMYEWJ5H00&activeTab=summary",
    "address": "3F1 10 Royal Crescent Edinburgh EH3 6PZ",
    "postcode": "EH3 6PZ",
    "received": "Received: Tue 22 Apr 2025",
    "validated": "Validated: Fri 23 May 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959701",
    "longitude": "-3.196156",
    "reference": "Ref. No: 25/02064/FULSTL",
    "title": "Retrospective change of use from residential flat, (Sui Generis) to short term let property (Sui Generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV01WEWITD00&activeTab=summary",
    "address": "2F1 122 Bruntsfield Place Bruntsfield Edinburgh EH10 4ES",
    "postcode": "EH10 4ES",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.93719",
    "longitude": "-3.207405",
    "reference": "Ref. No: 25/02023/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV05SEWIU900&activeTab=summary",
    "address": "Flat 20 128 Mcdonald Road Broughton Edinburgh EH7 4QU",
    "postcode": "EH7 4QU",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.964248",
    "longitude": "-3.186254",
    "reference": "Ref. No: 25/02033/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV06DEWIUF00&activeTab=summary",
    "address": "21A Royal Crescent Broughton Edinburgh EH3 6QA",
    "postcode": "EH3 6QA",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959417",
    "longitude": "-3.197653",
    "reference": "Ref. No: 25/02035/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV02BEWITG00&activeTab=summary",
    "address": "Flat 9 7 South Groathill Avenue Craigleith Edinburgh EH4 2LL",
    "postcode": "EH4 2LL",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957177",
    "longitude": "-3.244098",
    "reference": "Ref. No: 25/02024/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV034EWITL00&activeTab=summary",
    "address": "4F 100 Thirlestane Road Marchmont Edinburgh EH9 1AS",
    "postcode": "EH9 1AS",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.935555",
    "longitude": "-3.200054",
    "reference": "Ref. No: 25/02025/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV03JEWITO00&activeTab=summary",
    "address": "6 Hillside Crescent Hillside Edinburgh EH7 5DY",
    "postcode": "EH7 5DY",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958209",
    "longitude": "-3.180365",
    "reference": "Ref. No: 25/02026/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV04LEWITX00&activeTab=summary",
    "address": "Flat 70 124 Lothian Road West End Edinburgh EH3 9DD",
    "postcode": "EH3 9DD",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.945447",
    "longitude": "-3.205676",
    "reference": "Ref. No: 25/02029/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUV04XEWIU000&activeTab=summary",
    "address": "Flat 4 1 Powderhall Brae Warriston Edinburgh EH7 4GD",
    "postcode": "EH7 4GD",
    "received": "Received: Thu 17 Apr 2025",
    "validated": "Validated: Thu 17 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.967177",
    "longitude": "-3.195185",
    "reference": "Ref. No: 25/02030/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUT5DDEWIO400&activeTab=summary",
    "address": "16 Regent Place Abbeyhill Edinburgh EH7 5SB",
    "postcode": "EH7 5SB",
    "received": "Received: Wed 16 Apr 2025",
    "validated": "Validated: Tue 22 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958048",
    "longitude": "-3.168956",
    "reference": "Ref. No: 25/02008/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUR0WXEWIFJ00&activeTab=summary",
    "address": "18 East Norton Place Abbeyhill Edinburgh EH7 5DR",
    "postcode": "EH7 5DR",
    "received": "Received: Tue 15 Apr 2025",
    "validated": "Validated: Tue 29 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95736",
    "longitude": "-3.170859",
    "reference": "Ref. No: 25/01983/CLESTL",
    "title": "Continued use as Short Term Let (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SURHILEWII600&activeTab=summary",
    "address": "32A Prestonfield Avenue Prestonfield Edinburgh EH16 5EU",
    "postcode": "EH16 5EU",
    "received": "Received: Tue 15 Apr 2025",
    "validated": "Validated: Tue 15 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.932863",
    "longitude": "-3.158819",
    "reference": "Ref. No: 25/01993/FULSTL",
    "title": "Retrospective change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SURHIYEWIIC00&activeTab=summary",
    "address": "Flat 12 5 Dean Bank Lane Stockbridge Edinburgh EH3 5BS",
    "postcode": "EH3 5BS",
    "received": "Received: Tue 15 Apr 2025",
    "validated": "Validated: Wed 16 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959116",
    "longitude": "-3.208216",
    "reference": "Ref. No: 25/01994/FULSTL",
    "title": "Retrospective change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SURHJ4EWIII00&activeTab=summary",
    "address": "1F1 16 Marchmont Road Marchmont Edinburgh EH9 1HZ",
    "postcode": "EH9 1HZ",
    "received": "Received: Tue 15 Apr 2025",
    "validated": "Validated: Tue 15 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938871",
    "longitude": "-3.195402",
    "reference": "Ref. No: 25/01996/FULSTL",
    "title": "Retrospective change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SURHJ7EWIIN00&activeTab=summary",
    "address": "1F 51A Nicolson Street Newington Edinburgh EH8 9BZ",
    "postcode": "EH8 9BZ",
    "received": "Received: Tue 15 Apr 2025",
    "validated": "Validated: Wed 16 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.945518",
    "longitude": "-3.184896",
    "reference": "Ref. No: 25/01997/FULSTL",
    "title": "Retrospective change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUPG0GEWIBO00&activeTab=summary",
    "address": "1F2 74 Montpelier Park Bruntsfield Edinburgh EH10 4NG",
    "postcode": "EH10 4NG",
    "received": "Received: Mon 14 Apr 2025",
    "validated": "Validated: Mon 14 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.93773",
    "longitude": "-3.212785",
    "reference": "Ref. No: 25/01970/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUK2WAEWI5S00&activeTab=summary",
    "address": "99 East London Street Broughton Edinburgh EH7 4BF",
    "postcode": "EH7 4BF",
    "received": "Received: Fri 11 Apr 2025",
    "validated": "Validated: Fri 11 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960164",
    "longitude": "-3.184895",
    "reference": "Ref. No: 25/01949/FULSTL",
    "title": "Change of use from office (Class 4) to short term let accommodation (sui-generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SUJMAYEWI3100&activeTab=summary",
    "address": "10B Union Street Edinburgh EH1 3LU",
    "postcode": "EH1 3LU",
    "received": "Received: Fri 11 Apr 2025",
    "validated": "Validated: Wed 23 Apr 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957754",
    "longitude": "-3.186023",
    "reference": "Ref. No: 25/01936/FULSTL",
    "title": "Retrospective change of use from residential flat to short term let (sui generis)."
  }
];
  