
  export const PlanningApps = [
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSYK5REWL2R00&activeTab=summary",
    "address": "Flat 5 19A Brunswick Road Hillside Edinburgh EH7 5FN",
    "postcode": "EH7 5FN",
    "received": "Received: Tue 11 Mar 2025",
    "validated": "Validated: Tue 18 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960179",
    "longitude": "-3.17764",
    "reference": "Ref. No: 25/01277/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSWWCWEWKXV00&activeTab=summary",
    "address": "Flat 7A 5 Ramsay Garden Edinburgh EH1 2NA",
    "postcode": "EH1 2NA",
    "received": "Received: Mon 10 Mar 2025",
    "validated": "Validated: Tue 11 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949355",
    "longitude": "-3.196526",
    "reference": "Ref. No: 25/01259/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSR5E0EWKM600&activeTab=summary",
    "address": "Flat 5 255 Canongate Edinburgh EH8 8BQ",
    "postcode": "EH8 8BQ",
    "received": "Received: Fri 07 Mar 2025",
    "validated": "Validated: Fri 14 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950955",
    "longitude": "-3.182916",
    "reference": "Ref. No: 25/01204/FULSTL",
    "title": "Change of use (retrospective) from residential to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSPHNUEWKHO00&activeTab=summary",
    "address": "1F 129 Canongate Old Town Edinburgh EH8 8BP",
    "postcode": "EH8 8BP",
    "received": "Received: Thu 06 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951932",
    "longitude": "-3.178044",
    "reference": "Ref. No: 25/01189/FULSTL",
    "title": "Retrospective change of use from residential to short term let sui generis. Application for permission to continue the existing use of the property as commercial short stay accommodation short term letting."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSNG3PEWKA900&activeTab=summary",
    "address": "36 Northumberland Street New Town Edinburgh EH3 6JA",
    "postcode": "EH3 6JA",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.956921",
    "longitude": "-3.199659",
    "reference": "Ref. No: 25/01162/FULSTL",
    "title": "Change of use from residential apartment to short term let (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSNG30EWK9Z00&activeTab=summary",
    "address": "3F5 1 Upper Bow Edinburgh EH1 2JN",
    "postcode": "EH1 2JN",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Tue 11 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94898",
    "longitude": "-3.193921",
    "reference": "Ref. No: 25/01159/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSN6BUEWK8400&activeTab=summary",
    "address": "1F1 37A St Leonard's Street St Leonards Edinburgh EH8 9QN",
    "postcode": "EH8 9QN",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.943295",
    "longitude": "-3.180087",
    "reference": "Ref. No: 25/01152/CLESTL",
    "title": "Short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSN6BSEWK8100&activeTab=summary",
    "address": "1F3 1 Bailie Fyfe's Close 107 High Street Edinburgh EH1 1SW",
    "postcode": "EH1 1SW",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950586",
    "longitude": "-3.186331",
    "reference": "Ref. No: 25/01151/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSN6BJEWK7S00&activeTab=summary",
    "address": "Flat 5 30A Shandwick Place Edinburgh EH2 4RT",
    "postcode": "EH2 4RT",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Wed 19 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949736",
    "longitude": "-3.209941",
    "reference": "Ref. No: 25/01148/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSN6BEEWK7P00&activeTab=summary",
    "address": "45 Well Court Dean Edinburgh EH4 3BE",
    "postcode": "EH4 3BE",
    "received": "Received: Wed 05 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952132",
    "longitude": "-3.217976",
    "reference": "Ref. No: 25/01147/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLBNJEWK0P00&activeTab=summary",
    "address": "Flat 3 12 Old Tolbooth Wynd Old Town Edinburgh EH8 8EQ",
    "postcode": "EH8 8EQ",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952338",
    "longitude": "-3.180731",
    "reference": "Ref. No: 25/01120/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLBN8EWK0800&activeTab=summary",
    "address": "11 Sloan Street Leith Edinburgh EH6 8PL",
    "postcode": "EH6 8PL",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Mon 10 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.965588",
    "longitude": "-3.172644",
    "reference": "Ref. No: 25/01115/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLBN5EWK0500&activeTab=summary",
    "address": "1F2 70 South Clerk Street Newington Edinburgh EH8 9PT",
    "postcode": "EH8 9PT",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Tue 18 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.939802",
    "longitude": "-3.180383",
    "reference": "Ref. No: 25/01114/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLSCXEWK5A00&activeTab=summary",
    "address": "Flat 7 48 Annandale Street Broughton Edinburgh EH7 4FA",
    "postcode": "EH7 4FA",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.961456",
    "longitude": "-3.18596",
    "reference": "Ref. No: 25/01144/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLSCOEWK5400&activeTab=summary",
    "address": "Flat 12 50 Annandale Street Broughton Edinburgh EH7 4FA",
    "postcode": "EH7 4FA",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.961456",
    "longitude": "-3.18596",
    "reference": "Ref. No: 25/01142/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLSCMEWK5100&activeTab=summary",
    "address": "Flat 8 4 Carrubber's Close 135 High Street Edinburgh EH1 1SJ",
    "postcode": "EH1 1SJ",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950669",
    "longitude": "-3.187022",
    "reference": "Ref. No: 25/01141/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLSCFEWK4S00&activeTab=summary",
    "address": "1F2 152 Bruntsfield Place Edinburgh EH10 4ER",
    "postcode": "EH10 4ER",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Thu 13 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.936569",
    "longitude": "-3.208426",
    "reference": "Ref. No: 25/01138/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLSC6EWK4M00&activeTab=summary",
    "address": "2F1 377 Leith Walk Edinburgh EH6 8SE",
    "postcode": "EH6 8SE",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Mon 17 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.963582",
    "longitude": "-3.177565",
    "reference": "Ref. No: 25/01136/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSLLETEWK2Q00&activeTab=summary",
    "address": "1F4 30 Balfour Street Edinburgh EH6 5EP",
    "postcode": "EH6 5EP",
    "received": "Received: Tue 04 Mar 2025",
    "validated": "Validated: Thu 13 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.96674",
    "longitude": "-3.177084",
    "reference": "Ref. No: 25/01127/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJQX9EWJUW00&activeTab=summary",
    "address": "1F1 13 Union Street Broughton Edinburgh EH1 3LT",
    "postcode": "EH1 3LT",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958097",
    "longitude": "-3.185857",
    "reference": "Ref. No: 25/01105/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJQWUEWJUR00&activeTab=summary",
    "address": "PF1 9 Marchmont Street Marchmont Edinburgh EH9 1EL",
    "postcode": "EH9 1EL",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Mon 10 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938384",
    "longitude": "-3.20019",
    "reference": "Ref. No: 25/01104/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJXM8EWJW900&activeTab=summary",
    "address": "Flat 5 11 South Maybury Cammo Edinburgh EH12 8NX",
    "postcode": "EH12 8NX",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94209",
    "longitude": "-3.313358",
    "reference": "Ref. No: 25/01106/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJQWEEWJUM00&activeTab=summary",
    "address": "2F1 4 Hart Street Broughton Edinburgh EH1 3RN",
    "postcode": "EH1 3RN",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958428",
    "longitude": "-3.187917",
    "reference": "Ref. No: 25/01103/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJQW9EWJUJ00&activeTab=summary",
    "address": "Flat 6 101 East London Street Broughton Edinburgh EH7 4BF",
    "postcode": "EH7 4BF",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Mon 10 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960164",
    "longitude": "-3.184895",
    "reference": "Ref. No: 25/01102/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSJQVDEWJU200&activeTab=summary",
    "address": "22 Randolph Lane New Town Edinburgh EH3 7TD",
    "postcode": "EH3 7TD",
    "received": "Received: Mon 03 Mar 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952153",
    "longitude": "-3.209969",
    "reference": "Ref. No: 25/01097/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSDX10EWJIS00&activeTab=summary",
    "address": "GF 23 Dean Park Mews Stockbridge Edinburgh EH4 1EE",
    "postcode": "EH4 1EE",
    "received": "Received: Fri 28 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.958091",
    "longitude": "-3.21552",
    "reference": "Ref. No: 25/01058/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSDX0GEWJIG00&activeTab=summary",
    "address": "1F1 66 Whitson Road Stenhouse Edinburgh EH11 3BS",
    "postcode": "EH11 3BS",
    "received": "Received: Fri 28 Feb 2025",
    "validated": "Validated: Wed 12 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.936427",
    "longitude": "-3.254142",
    "reference": "Ref. No: 25/01054/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSCJ0VEWJFO00&activeTab=summary",
    "address": "1F2 5 East London Street Broughton Edinburgh EH7 4BN",
    "postcode": "EH7 4BN",
    "received": "Received: Thu 27 Feb 2025",
    "validated": "Validated: Tue 18 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959294",
    "longitude": "-3.189865",
    "reference": "Ref. No: 25/01050/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSCJ0OEWJFI00&activeTab=summary",
    "address": "Flat 1 50 North Bridge Edinburgh EH1 1QN",
    "postcode": "EH1 1QN",
    "received": "Received: Thu 27 Feb 2025",
    "validated": "Validated: Tue 11 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95047",
    "longitude": "-3.188057",
    "reference": "Ref. No: 25/01048/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSCJ0FEWJFD00&activeTab=summary",
    "address": "Flat 8 10 Bernard Street North Leith Edinburgh EH6 6PP",
    "postcode": "EH6 6PP",
    "received": "Received: Thu 27 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.975913",
    "longitude": "-3.167237",
    "reference": "Ref. No: 25/01047/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSCCA3EWJE600&activeTab=summary",
    "address": "Flat 10 1 Allanfield Place Hillside Edinburgh EH7 5AG",
    "postcode": "EH7 5AG",
    "received": "Received: Thu 27 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960937",
    "longitude": "-3.175082",
    "reference": "Ref. No: 25/01043/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSCC9IEWJDU00&activeTab=summary",
    "address": "Flat 7 15 Lochend Park View Edinburgh EH7 5FX",
    "postcode": "EH7 5FX",
    "received": "Received: Thu 27 Feb 2025",
    "validated": "Validated: Thu 27 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959379",
    "longitude": "-3.16214",
    "reference": "Ref. No: 25/01039/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years"
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHHNEWJ5A00&activeTab=summary",
    "address": "2F2 5 Royal Crescent Edinburgh EH3 6PZ",
    "postcode": "EH3 6PZ",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Fri 14 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959701",
    "longitude": "-3.196156",
    "reference": "Ref. No: 25/00999/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHHEEWJ5700&activeTab=summary",
    "address": "1F2 5 Gibson Terrace Polwarth Edinburgh EH11 1AU",
    "postcode": "EH11 1AU",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.940309",
    "longitude": "-3.217348",
    "reference": "Ref. No: 25/00998/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSA7ODEWJ3B00&activeTab=summary",
    "address": "1F3 107 Broughton Road Warriston Edinburgh EH7 4EG",
    "postcode": "EH7 4EG",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Mon 03 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.96435",
    "longitude": "-3.193",
    "reference": "Ref. No: 25/00987/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHIDEWJ5Q00&activeTab=summary",
    "address": "1F3 36 Roseburn Street Roseburn Edinburgh EH12 5PN",
    "postcode": "EH12 5PN",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Wed 12 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.943867",
    "longitude": "-3.235473",
    "reference": "Ref. No: 25/01004/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHI1EWJ5J00&activeTab=summary",
    "address": "1F1 18 Waverley Park Abbeyhill Edinburgh EH8 8ET",
    "postcode": "EH8 8ET",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Tue 04 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954331",
    "longitude": "-3.167691",
    "reference": "Ref. No: 25/01002/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSA7P2EWJ3Z00&activeTab=summary",
    "address": "2F2 10 West Newington Place Newington Edinburgh EH9 1QT",
    "postcode": "EH9 1QT",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Fri 07 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.937828",
    "longitude": "-3.179617",
    "reference": "Ref. No: 25/00995/CLESTL",
    "title": "Use as a short term let property as an existing user."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSA7OPEWJ3N00&activeTab=summary",
    "address": "Flat 5 28 East Fountainbridge Tollcross Edinburgh EH3 9BH",
    "postcode": "EH3 9BH",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Tue 18 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94541",
    "longitude": "-3.203914",
    "reference": "Ref. No: 25/00991/CLESTL",
    "title": "Short term letting."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHHXEWJ5G00&activeTab=summary",
    "address": "GF1 26 Calton Hill Edinburgh EH1 3BJ",
    "postcode": "EH1 3BJ",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Mon 03 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.954507",
    "longitude": "-3.185938",
    "reference": "Ref. No: 25/01001/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHHTEWJ5D00&activeTab=summary",
    "address": "4F2 8 Jeffrey Street Edinburgh EH1 1DT",
    "postcode": "EH1 1DT",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Wed 12 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950993",
    "longitude": "-3.184165",
    "reference": "Ref. No: 25/01000/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSA7O6EWJ3000&activeTab=summary",
    "address": "25 Gloucester Lane Edinburgh EH3 6ED",
    "postcode": "EH3 6ED",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Tue 11 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.955452",
    "longitude": "-3.206597",
    "reference": "Ref. No: 25/00984/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSA7NREWJ2M00&activeTab=summary",
    "address": "Flat 7 47 Blackfriars Street Edinburgh EH1 1NB",
    "postcode": "EH1 1NB",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949658",
    "longitude": "-3.18563",
    "reference": "Ref. No: 25/00980/FULSTL",
    "title": "Retrospective change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHIWEWJ6700&activeTab=summary",
    "address": "Flat 37 9 Salamander Court South Leith Edinburgh EH6 7JP",
    "postcode": "EH6 7JP",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.974592",
    "longitude": "-3.1621",
    "reference": "Ref. No: 25/01009/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SSAHIUEWJ6400&activeTab=summary",
    "address": "1F4 34 Broughton Road Warriston Edinburgh EH7 4ED",
    "postcode": "EH7 4ED",
    "received": "Received: Wed 26 Feb 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.9634",
    "longitude": "-3.19454",
    "reference": "Ref. No: 25/01008/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8TOJEWJ0400&activeTab=summary",
    "address": "7 Cordiner's Land Tollcross Edinburgh EH1 2LF",
    "postcode": "EH1 2LF",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Tue 04 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946248",
    "longitude": "-3.200017",
    "reference": "Ref. No: 25/00978/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8TNXEWIZR00&activeTab=summary",
    "address": "82 East Crosscauseway Edinburgh EH8 9HQ",
    "postcode": "EH8 9HQ",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Wed 12 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.944037",
    "longitude": "-3.181423",
    "reference": "Ref. No: 25/00975/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8D0QEWIVE00&activeTab=summary",
    "address": "Flat 1 12 Lady Lawson Street Old Town Edinburgh EH3 9DS",
    "postcode": "EH3 9DS",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Tue 25 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946251",
    "longitude": "-3.201586",
    "reference": "Ref. No: 25/00957/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use as a short term let visitor accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8D0IEWIV500&activeTab=summary",
    "address": "Flat 4 124 Lothian Road Edinburgh EH3 9BG",
    "postcode": "EH3 9BG",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Tue 04 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.945393",
    "longitude": "-3.205659",
    "reference": "Ref. No: 25/00954/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8D08EWIUU00&activeTab=summary",
    "address": "1F3 8 Livingstone Place Sciennes Edinburgh EH9 1PA",
    "postcode": "EH9 1PA",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Fri 07 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938437",
    "longitude": "-3.186359",
    "reference": "Ref. No: 25/00951/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8D02EWIUO00&activeTab=summary",
    "address": "2F4 23 Forbes Road Edinburgh EH10 4EG",
    "postcode": "EH10 4EG",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Fri 28 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.936509",
    "longitude": "-3.207224",
    "reference": "Ref. No: 25/00949/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8CZYEWIUL00&activeTab=summary",
    "address": "GF 33 Northumberland Street New Town Edinburgh EH3 6LR",
    "postcode": "EH3 6LR",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Tue 04 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957186",
    "longitude": "-3.198258",
    "reference": "Ref. No: 25/00948/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8CZHEWIU500&activeTab=summary",
    "address": "301 Webster's Land Edinburgh EH1 2RU",
    "postcode": "EH1 2RU",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Mon 03 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946598",
    "longitude": "-3.199548",
    "reference": "Ref. No: 25/00944/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8TNNEWIZG00&activeTab=summary",
    "address": "BF2 31 Angle Park Terrace Gorgie Edinburgh EH11 2JT",
    "postcode": "EH11 2JT",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Fri 07 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938029",
    "longitude": "-3.225281",
    "reference": "Ref. No: 25/00972/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8MSEEWIY300&activeTab=summary",
    "address": "3F2 62 Thistle Street New Town Edinburgh EH2 1EN",
    "postcode": "EH2 1EN",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953847",
    "longitude": "-3.199387",
    "reference": "Ref. No: 25/00968/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8MRBEWIXP00&activeTab=summary",
    "address": "PF1 13 Gladstone Terrace Sciennes Edinburgh EH9 1LT",
    "postcode": "EH9 1LT",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Mon 10 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938283",
    "longitude": "-3.18557",
    "reference": "Ref. No: 25/00964/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8MQSEWIXJ00&activeTab=summary",
    "address": "1F1 186 Rose Street New Town Edinburgh EH2 4BA",
    "postcode": "EH2 4BA",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Mon 10 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.951426",
    "longitude": "-3.204341",
    "reference": "Ref. No: 25/00962/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS8MSREWIY900&activeTab=summary",
    "address": "1F2 13 Gladstone Terrace Sciennes Edinburgh EH9 1LT",
    "postcode": "EH9 1LT",
    "received": "Received: Tue 25 Feb 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.938283",
    "longitude": "-3.18557",
    "reference": "Ref. No: 25/00970/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS6IBDEWIO300&activeTab=summary",
    "address": "Flat 1 4 Dalry Gait Dalry Edinburgh EH11 2AU",
    "postcode": "EH11 2AU",
    "received": "Received: Mon 24 Feb 2025",
    "validated": "Validated: Mon 24 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.944521",
    "longitude": "-3.219434",
    "reference": "Ref. No: 25/00920/CLESTL",
    "title": "Short Term Let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SS0YC5EWIG200&activeTab=summary",
    "address": "1F1 11 Ormiston Terrace Edinburgh EH12 7SJ",
    "postcode": "EH12 7SJ",
    "received": "Received: Fri 21 Feb 2025",
    "validated": "Validated: Mon 24 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942738",
    "longitude": "-3.283503",
    "reference": "Ref. No: 25/00890/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRZ3NQEWI9H00&activeTab=summary",
    "address": "Flat 5 5 Warriston Road Warriston Edinburgh EH3 5LQ",
    "postcode": "EH3 5LQ",
    "received": "Received: Thu 20 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.9632",
    "longitude": "-3.198491",
    "reference": "Ref. No: 25/00865/FULSTL",
    "title": "Change of use of residential property to short term let (in retrospect)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRZ3NEEWI8X00&activeTab=summary",
    "address": "618 Webster's Land Tollcross Edinburgh EH1 2RX",
    "postcode": "EH1 2RX",
    "received": "Received: Thu 20 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946589",
    "longitude": "-3.199548",
    "reference": "Ref. No: 25/00859/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRZ3NCEWI8U00&activeTab=summary",
    "address": "2F1 129 Rose Street New Town Edinburgh EH2 3DT",
    "postcode": "EH2 3DT",
    "received": "Received: Thu 20 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952128",
    "longitude": "-3.201512",
    "reference": "Ref. No: 25/00858/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRXIR7EWI4A00&activeTab=summary",
    "address": "1F1 6 Drumdryan Street Tollcross Edinburgh EH3 9LA",
    "postcode": "EH3 9LA",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Mon 03 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942671",
    "longitude": "-3.202804",
    "reference": "Ref. No: 25/00845/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRX8YGEWI2M00&activeTab=summary",
    "address": "47 Brunswick Street Edinburgh EH7 5HT",
    "postcode": "EH7 5HT",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Wed 26 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959918",
    "longitude": "-3.180113",
    "reference": "Ref. No: 25/00839/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRX8YFEWI2J00&activeTab=summary",
    "address": "Flat 4 4 Old Assembly Close 172 High Street Edinburgh EH1 1QX",
    "postcode": "EH1 1QX",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Tue 25 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949729",
    "longitude": "-3.189411",
    "reference": "Ref. No: 25/00838/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRX8YDEWI2G00&activeTab=summary",
    "address": "32A Haddington Place Broughton Edinburgh EH7 4AG",
    "postcode": "EH7 4AG",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960613",
    "longitude": "-3.182074",
    "reference": "Ref. No: 25/00837/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRX8Y7EWI2D00&activeTab=summary",
    "address": "1F3 11 Comely Bank Road Stockbridge Edinburgh EH4 1DR",
    "postcode": "EH4 1DR",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Wed 19 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959158",
    "longitude": "-3.214848",
    "reference": "Ref. No: 25/00836/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRXPO4EWI6E00&activeTab=summary",
    "address": "Flat 4 12 Calder View Calders Edinburgh EH11 4HX",
    "postcode": "EH11 4HX",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Thu 27 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.920179",
    "longitude": "-3.298551",
    "reference": "Ref. No: 25/00854/FULSTL",
    "title": "Change of use from flat( sui generis) to short term let (Sui Generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRXPO1EWI6B00&activeTab=summary",
    "address": "3F3 37 Montgomery Street Hillside Edinburgh EH7 5JX",
    "postcode": "EH7 5JX",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Wed 19 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959488",
    "longitude": "-3.180917",
    "reference": "Ref. No: 25/00853/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years"
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRXPNHEWI5Z00&activeTab=summary",
    "address": "2F2 56 Dublin Street New Town Edinburgh EH3 6NP",
    "postcode": "EH3 6NP",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95785",
    "longitude": "-3.194305",
    "reference": "Ref. No: 25/00849/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRXPNAEWI5W00&activeTab=summary",
    "address": "Flat 3 5 Gilmour's Entry Newington Edinburgh EH8 9XL",
    "postcode": "EH8 9XL",
    "received": "Received: Wed 19 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.944731",
    "longitude": "-3.182165",
    "reference": "Ref. No: 25/00848/CLESTL",
    "title": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation for a period over 10 years."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVECGEWHXP00&activeTab=summary",
    "address": "2F3 1 South Charlotte Street New Town Edinburgh EH2 4AN",
    "postcode": "EH2 4AN",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950922",
    "longitude": "-3.205767",
    "reference": "Ref. No: 25/00819/FULSTL",
    "title": "Change of use (retrospective) from office space to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVECDEWHXM00&activeTab=summary",
    "address": "2F2 1 South Charlotte Street New Town Edinburgh EH2 4AN",
    "postcode": "EH2 4AN",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950922",
    "longitude": "-3.205767",
    "reference": "Ref. No: 25/00818/FULSTL",
    "title": "Change of use (retrospective) from office space to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVECBEWHXJ00&activeTab=summary",
    "address": "1F4 1 South Charlotte Street New Town Edinburgh EH2 4AN",
    "postcode": "EH2 4AN",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950922",
    "longitude": "-3.205767",
    "reference": "Ref. No: 25/00817/FULSTL",
    "title": "Change of use (retrospective) from storage space to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVEC9EWHXG00&activeTab=summary",
    "address": "1F2 1 South Charlotte Street New Town Edinburgh EH2 4AN",
    "postcode": "EH2 4AN",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950922",
    "longitude": "-3.205767",
    "reference": "Ref. No: 25/00816/FULSTL",
    "title": "Change of use (retrospective) from storage space to short term let accommodation (sui generis)."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVEBZEWHX400&activeTab=summary",
    "address": "115 Pitt Street Bonnington Edinburgh EH6 4DE",
    "postcode": "EH6 4DE",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.973703",
    "longitude": "-3.184651",
    "reference": "Ref. No: 25/00813/FULSTL",
    "title": "Change of use from dwelling to short term let."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVEBXEWHX100&activeTab=summary",
    "address": "Flat 5 30 West Crosscauseway Newington Edinburgh EH8 9JP",
    "postcode": "EH8 9JP",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Fri 21 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.943902",
    "longitude": "-3.184269",
    "reference": "Ref. No: 25/00812/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVEBNEWHWQ00&activeTab=summary",
    "address": "Flat 5 8 Porteous' Pend Old Town Edinburgh EH1 2HP",
    "postcode": "EH1 2HP",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946869",
    "longitude": "-3.197138",
    "reference": "Ref. No: 25/00809/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVV05EWI1000&activeTab=summary",
    "address": "Flat 11 2 Albion Gardens Leith Edinburgh EH7 5QF",
    "postcode": "EH7 5QF",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Mon 17 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960381",
    "longitude": "-3.166431",
    "reference": "Ref. No: 25/00834/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRVUZHEWI0V00&activeTab=summary",
    "address": "Flat 2 19 Old Fishmarket Close 190 High Street Edinburgh EH1 1RW",
    "postcode": "EH1 1RW",
    "received": "Received: Tue 18 Feb 2025",
    "validated": "Validated: Thu 20 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949684",
    "longitude": "-3.18994",
    "reference": "Ref. No: 25/00833/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRO9GUEWHLC00&activeTab=summary",
    "address": "1F1 38 Cockburn Street Edinburgh EH1 1PB",
    "postcode": "EH1 1PB",
    "received": "Received: Fri 14 Feb 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950461",
    "longitude": "-3.189451",
    "reference": "Ref. No: 25/00771/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRO9GREWHL900&activeTab=summary",
    "address": "Flat 2 5 Lady Wynd Edinburgh EH1 2LH",
    "postcode": "EH1 2LH",
    "received": "Received: Fri 14 Feb 2025",
    "validated": "Validated: Thu 06 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.94691",
    "longitude": "-3.198404",
    "reference": "Ref. No: 25/00770/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKK51EWH8Q00&activeTab=summary",
    "address": "2F3 19 Montgomery Street Edinburgh EH7 5JU",
    "postcode": "EH7 5JU",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Fri 07 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959403",
    "longitude": "-3.182308",
    "reference": "Ref. No: 25/00733/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKABSEWH5K00&activeTab=summary",
    "address": "Flat 2 2 Cowgatehead Edinburgh EH1 1JU",
    "postcode": "EH1 1JU",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Mon 24 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.947944",
    "longitude": "-3.193808",
    "reference": "Ref. No: 25/00714/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKACDEWH6D00&activeTab=summary",
    "address": "2F1 100 West Bow Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Fri 14 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.948217",
    "longitude": "-3.194297",
    "reference": "Ref. No: 25/00723/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKACBEWH6A00&activeTab=summary",
    "address": "Flat 7 11 Old Fishmarket Close 190 High Street Edinburgh EH1 1RW",
    "postcode": "EH1 1RW",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949684",
    "longitude": "-3.18994",
    "reference": "Ref. No: 25/00722/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKAC4EWH5Y00&activeTab=summary",
    "address": "1F1 9 High Street Edinburgh EH1 1SR",
    "postcode": "EH1 1SR",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Mon 17 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95078",
    "longitude": "-3.184799",
    "reference": "Ref. No: 25/00718/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKAC2EWH5V00&activeTab=summary",
    "address": "1F3 60 St Mary's Street Edinburgh EH1 1SX",
    "postcode": "EH1 1SX",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Tue 18 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949619",
    "longitude": "-3.183098",
    "reference": "Ref. No: 25/00717/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKK4KEWH8H00&activeTab=summary",
    "address": "Flat 2 71 Canongate Edinburgh EH8 8BS",
    "postcode": "EH8 8BS",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Tue 11 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952334",
    "longitude": "-3.176391",
    "reference": "Ref. No: 25/00730/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRKK4DEWH8C00&activeTab=summary",
    "address": "25A Howe Street Edinburgh EH3 6TF",
    "postcode": "EH3 6TF",
    "received": "Received: Wed 12 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.956731",
    "longitude": "-3.202135",
    "reference": "Ref. No: 25/00729/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIFPDEWGXY00&activeTab=summary",
    "address": "4 Broughton Street Lane Edinburgh EH1 3LY",
    "postcode": "EH1 3LY",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Fri 14 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957501",
    "longitude": "-3.187072",
    "reference": "Ref. No: 25/00687/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIPFXEWH1200&activeTab=summary",
    "address": "75 Brunswick Street Edinburgh EH7 5HS",
    "postcode": "EH7 5HS",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Mon 17 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960374",
    "longitude": "-3.180351",
    "reference": "Ref. No: 25/00702/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIFPLEWGYC00&activeTab=summary",
    "address": "2F2 4 Springvalley Terrace Edinburgh EH10 4QD",
    "postcode": "EH10 4QD",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Thu 13 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.928835",
    "longitude": "-3.210938",
    "reference": "Ref. No: 25/00691/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIFPIEWGY600&activeTab=summary",
    "address": "Flat 1 15 Great Stuart Street Edinburgh EH3 7TP",
    "postcode": "EH3 7TP",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Wed 12 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952669",
    "longitude": "-3.211378",
    "reference": "Ref. No: 25/00689/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIFOBEWGWO00&activeTab=summary",
    "address": "7 Great King Street Edinburgh EH3 6QW",
    "postcode": "EH3 6QW",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Wed 05 Mar 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.957893",
    "longitude": "-3.197719",
    "reference": "Ref. No: 25/00679/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIFNBEWGVY00&activeTab=summary",
    "address": "145A Drum Street Edinburgh EH17 8RX",
    "postcode": "EH17 8RX",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Tue 11 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.906969",
    "longitude": "-3.119238",
    "reference": "Ref. No: 25/00673/CLESTL",
    "title": "Use of house for short term let use."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIWC5EWH2X00&activeTab=summary",
    "address": "68A Dalry Road Edinburgh EH11 2AY",
    "postcode": "EH11 2AY",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Fri 14 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.944429",
    "longitude": "-3.218295",
    "reference": "Ref. No: 25/00711/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  },
  {
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SRIWBZEWH2R00&activeTab=summary",
    "address": "Flat 11 87 East London Street Edinburgh EH7 4BQ",
    "postcode": "EH7 4BQ",
    "received": "Received: Tue 11 Feb 2025",
    "validated": "Validated: Fri 28 Feb 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.960003",
    "longitude": "-3.186298",
    "reference": "Ref. No: 25/00709/FULSTL",
    "title": "Retrospective change of use of premises to short term let accommodation."
  }
];
  