export const PlanningApps = [{
  "title": `Short term let (change of use to short term let took place with the last 10 years but it is not material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1W4XEEWMDM00&activeTab=summary`,
  "postcode": `EH7 5HE`,
  "address": `1F3 98 Montgomery Street Edinburgh EH7 5HE`,
  "reference": `23/05562/CLESTL`,
  "received": `Mon 02 Oct 2023`,
  "validated": `Mon 02 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.959183`,
  "longitude": `-3.177127`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1QKZEEWLSB00&activeTab=summary`,
  "postcode": `EH1 1QS`,
  "address": `2F 150 High Street Edinburgh EH1 1QS`,
  "reference": `23/05374/CLESTL`,
  "received": `Fri 29 Sep 2023`,
  "validated": `Fri 29 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.94979`,
  "longitude": `-3.188708`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1QKWJEWLPO00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Unit 10 219 High Street Edinburgh EH1 1PE`,
  "reference": `23/05348/CLESTL`,
  "received": `Fri 29 Sep 2023`,
  "validated": `Fri 29 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1QKZ6EWLS800&activeTab=summary`,
  "postcode": `EH1 2NA`,
  "address": `7 Ramsay Garden Edinburgh EH1 2NA`,
  "reference": `23/05373/CLESTL`,
  "received": `Fri 29 Sep 2023`,
  "validated": `Fri 29 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.949355`,
  "longitude": `-3.196526`,
  },
  
  {
  "title": `Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQAXEWL9A00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Unit 6 219 High Street Old Town Edinburgh EH1 1PE`,
  "reference": `23/05209/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Change of use from dwellinghouse to short term let - secondary letting.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQA9EWL8U00&activeTab=summary`,
  "postcode": `EH5 2PF`,
  "address": `163 Crewe Road West Edinburgh EH5 2PF`,
  "reference": `23/05205/FULSTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 19 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.975409`,
  "longitude": `-3.240517`,
  },
  
  {
  "title": `Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQCJEWLAU00&activeTab=summary`,
  "postcode": `EH10 4ER`,
  "address": `1F2 152 Bruntsfield Place Bruntsfield Edinburgh EH10 4ER`,
  "reference": `23/05227/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.936569`,
  "longitude": `-3.208426`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQA2EWL8I00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Flat 11 219 High Street Old Town Edinburgh EH1 1PE`,
  "reference": `23/05201/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OZXBEWLHP00&activeTab=summary`,
  "postcode": `EH8 9HG`,
  "address": `2F1 51 East Crosscauseway Edinburgh EH8 9HG`,
  "reference": `23/05293/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.943591`,
  "longitude": `-3.182098`,
  },
  
  {
  "title": `Use of flatted dwelling as short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1P6W4EWLKX00&activeTab=summary`,
  "postcode": `EH1 1PB`,
  "address": `2F1 38 Cockburn Street Old Town Edinburgh EH1 1PB`,
  "reference": `23/05318/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 12 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950461`,
  "longitude": `-3.189451`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQFQEWLD900&activeTab=summary`,
  "postcode": `EH1 1QS`,
  "address": `3F 150 High Street Old Town Edinburgh EH1 1QS`,
  "reference": `23/05256/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.94979`,
  "longitude": `-3.188708`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQG5EWLDX00&activeTab=summary`,
  "postcode": `EH8 8EU`,
  "address": `PF3 12 Waverley Park Abbeyhill Edinburgh EH8 8EU`,
  "reference": `23/05264/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.95473`,
  "longitude": `-3.16727`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQ83EWL7Q00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Unit 5 219 High Street Edinburgh EH1 1PE`,
  "reference": `23/05191/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Short Term Let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQCTEWLBC00&activeTab=summary`,
  "postcode": `EH7 5NP`,
  "address": `Flat 13 8 Albion Gardens Leith Edinburgh EH7 5NP`,
  "reference": `23/05233/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.960315`,
  "longitude": `-3.164843`,
  },
  
  {
  "title": `Use of flatted dwelling as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1P6XQEWLM800&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Flat 3 227 High Street Edinburgh EH1 1PE`,
  "reference": `23/05333/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Application for a certificate of lawfulness for a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQG4EWLDU00&activeTab=summary`,
  "postcode": `EH3 5AA`,
  "address": `PF2 142 St Stephen Street Stockbridge Edinburgh EH3 5AA`,
  "reference": `23/05263/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.958392`,
  "longitude": `-3.204173`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQG2EWLDR00&activeTab=summary`,
  "postcode": `EH7 5JU`,
  "address": `1F3 3 Montgomery Street Hillside Edinburgh EH7 5JU`,
  "reference": `23/05262/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.959403`,
  "longitude": `-3.182308`,
  },
  
  {
  "title": `Use of flatted dwelling as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1P6XLEWLM200&activeTab=summary`,
  "postcode": `EH1 1BS`,
  "address": `Flat 13 51 Cockburn Street Old Town Edinburgh EH1 1BS`,
  "reference": `23/05331/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Wed 18 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.95072`,
  "longitude": `-3.189137`,
  },
  
  {
  "title": `Use of flatted dwelling as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1P6XTEWLMB00&activeTab=summary`,
  "postcode": `EH1 2RU`,
  "address": `201 Webster's Land Tollcross Edinburgh EH1 2RU`,
  "reference": `23/05334/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.946598`,
  "longitude": `-3.199548`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQH3EWLF300&activeTab=summary`,
  "postcode": `EH8 9UW`,
  "address": `41 Viewcraig Gardens Edinburgh EH8 9UW`,
  "reference": `23/05278/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.947038`,
  "longitude": `-3.179561`,
  },
  
  {
  "title": `Certificate of lawfulness is sought for use of flatted dwellling as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1P6WMEWLLE00&activeTab=summary`,
  "postcode": `EH1 2QN`,
  "address": `1F1 6 Forrest Road Old Town Edinburgh EH1 2QN`,
  "reference": `23/05323/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.945811`,
  "longitude": `-3.190846`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQG0EWLDO00&activeTab=summary`,
  "postcode": `EH3 8AU`,
  "address": `3F1 16 Upper Grove Place Fountainbridge Edinburgh EH3 8AU`,
  "reference": `23/05261/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.943914`,
  "longitude": `-3.21261`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQEFEWLCU00&activeTab=summary`,
  "postcode": `EH16 5EU`,
  "address": `32A Prestonfield Avenue Prestonfield Edinburgh EH16 5EU`,
  "reference": `23/05251/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.932863`,
  "longitude": `-3.158819`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQEJEWLD000&activeTab=summary`,
  "postcode": `EH3 5BS`,
  "address": `Flat 12 5 Dean Bank Lane Stockbridge Edinburgh EH3 5BS`,
  "reference": `23/05253/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.959116`,
  "longitude": `-3.208216`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQGCEWLE600&activeTab=summary`,
  "postcode": `EH9 1HZ`,
  "address": `1F1 16 Marchmont Road Marchmont Edinburgh EH9 1HZ`,
  "reference": `23/05267/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 28 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.938871`,
  "longitude": `-3.195402`,
  },
  
  {
  "title": `Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1OQBMEWL9M00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Unit 7 219 High Street Old Town Edinburgh EH1 1PE`,
  "reference": `23/05213/CLESTL`,
  "received": `Thu 28 Sep 2023`,
  "validated": `Thu 12 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVQWEWKYQ00&activeTab=summary`,
  "postcode": `EH3 5QU`,
  "address": `1A Royston Terrace Edinburgh EH3 5QU`,
  "reference": `23/05131/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.970668`,
  "longitude": `-3.207598`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1N5AIEWL0T00&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Unit 3 219 High Street Edinburgh EH1 1PE`,
  "reference": `23/05141/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Thu 12 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Existing use as short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVNBEWKVC00&activeTab=summary`,
  "postcode": `EH2 4AN`,
  "address": `1F4 1 South Charlotte Street Edinburgh EH2 4AN`,
  "reference": `23/05094/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Thu 12 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950922`,
  "longitude": `-3.205767`,
  },
  
  {
  "title": `Short term let (see supporting statement).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVK6EWKS700&activeTab=summary`,
  "postcode": `EH11 1UJ`,
  "address": `1F3 44 Stewart Terrace Edinburgh EH11 1UJ`,
  "reference": `23/05058/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.934737`,
  "longitude": `-3.232829`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVMYEWKUV00&activeTab=summary`,
  "postcode": `EH3 6LF`,
  "address": `9 Nelson Street Edinburgh EH3 6LF`,
  "reference": `23/05089/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.957016`,
  "longitude": `-3.195977`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1N5B4EWL1B00&activeTab=summary`,
  "postcode": `EH4 1JD`,
  "address": `25 Cheyne Street Edinburgh EH4 1JD`,
  "reference": `23/05145/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Tue 10 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.958859`,
  "longitude": `-3.212789`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVMIEWKUJ00&activeTab=summary`,
  "postcode": `EH3 7RN`,
  "address": `23B Drumsheugh Gardens Edinburgh EH3 7RN`,
  "reference": `23/05085/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.951325`,
  "longitude": `-3.214235`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1MVOBEWKWJ00&activeTab=summary`,
  "postcode": `EH3 6SS`,
  "address": `18B Royal Circus Edinburgh EH3 6SS`,
  "reference": `23/05108/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.957572`,
  "longitude": `-3.205333`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1N5AXEWL1500&activeTab=summary`,
  "postcode": `EH9 1PY`,
  "address": `58 Causewayside Edinburgh EH9 1PY`,
  "reference": `23/05143/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.938013`,
  "longitude": `-3.181401`,
  },
  
  {
  "title": `Short term let use.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1NC84EWL4C00&activeTab=summary`,
  "postcode": `EH8 8HF`,
  "address": `Flat 2 4 Milton Street Edinburgh EH8 8HF`,
  "reference": `23/05171/CLESTL`,
  "received": `Wed 27 Sep 2023`,
  "validated": `Wed 27 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.95511`,
  "longitude": `-3.168018`,
  },
  
  {
  "title": `To continue operating as a Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0WPEWKE800&activeTab=summary`,
  "postcode": `EH8 8EQ`,
  "address": `Flat 5 8 Old Tolbooth Wynd Edinburgh EH8 8EQ`,
  "reference": `23/04945/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.952338`,
  "longitude": `-3.180731`,
  },
  
  {
  "title": `Ongoing use as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1LAMSEWKIY00&activeTab=summary`,
  "postcode": `EH8 8BP`,
  "address": `1F 129 Canongate Edinburgh EH8 8BP`,
  "reference": `23/04999/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Thu 19 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.951932`,
  "longitude": `-3.178044`,
  },
  
  {
  "title": `Existing use of the property as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0YKEWKFD00&activeTab=summary`,
  "postcode": `EH1 1SJ`,
  "address": `Flat 9 4 Carrubber's Close 135 High Street Edinburgh EH1 1SJ`,
  "reference": `23/04958/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950669`,
  "longitude": `-3.187022`,
  },
  
  {
  "title": `Retrospective change of use to short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0YPEWKFJ00&activeTab=summary`,
  "postcode": `EH1 2JY`,
  "address": `1F3 13 King's Stables Road Edinburgh EH1 2JY`,
  "reference": `23/04960/FULSTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.947166`,
  "longitude": `-3.200287`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place within the last 10 years but is not a material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1LHMNEWKOP00&activeTab=summary`,
  "postcode": `EH1 1SU`,
  "address": `2F2 12 St Mary's Street Old Town Edinburgh EH1 1SU`,
  "reference": `23/05042/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950369`,
  "longitude": `-3.183618`,
  },
  
  {
  "title": `Property has been run as a short term let from December 2021 since completion of the property.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0ZDEWKG500&activeTab=summary`,
  "postcode": `EH1 3RS`,
  "address": `12 Broughton Place Lane Edinburgh EH1 3RS`,
  "reference": `23/04967/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Thu 19 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.95909`,
  "longitude": `-3.189107`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0YVEWKFQ00&activeTab=summary`,
  "postcode": `EH7 4ET`,
  "address": `27 Beaverbank Place Edinburgh EH7 4ET`,
  "reference": `23/04962/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 10 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.96404`,
  "longitude": `-3.194368`,
  },
  
  {
  "title": `Continued use as short term let which has been operating since January 1999.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L10SEWKH800&activeTab=summary`,
  "postcode": `EH1 2PR`,
  "address": `1F2 16 Johnston Terrace Edinburgh EH1 2PR`,
  "reference": `23/04980/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Thu 26 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.948549`,
  "longitude": `-3.196197`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0Z0EWKFW00&activeTab=summary`,
  "postcode": `EH7 4ET`,
  "address": `28 Beaverbank Place Warriston Edinburgh EH7 4ET`,
  "reference": `23/04964/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.96404`,
  "longitude": `-3.194368`,
  },
  
  {
  "title": `Residential flat with short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L11DEWKHT00&activeTab=summary`,
  "postcode": `EH1 1QN`,
  "address": `Flat 6 50 North Bridge Old Town Edinburgh EH1 1QN`,
  "reference": `23/04987/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.95047`,
  "longitude": `-3.188057`,
  },
  
  {
  "title": `Use as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0W0EWKDT00&activeTab=summary`,
  "postcode": `EH1 3AT`,
  "address": `Flat 2 35 Leith Street New Town Edinburgh EH1 3AT`,
  "reference": `23/04940/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.954045`,
  "longitude": `-3.187639`,
  },
  
  {
  "title": `To continue operating as a Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L10FEWKGW00&activeTab=summary`,
  "postcode": `EH1 2HH`,
  "address": `3F3 86 West Bow Edinburgh EH1 2HH`,
  "reference": `23/04976/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.948217`,
  "longitude": `-3.194297`,
  },
  
  {
  "title": `It is presented that the property benefits from lawful use for operating as short term lets, a use also known as self-catering accommodation and airbnb.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0XTEWKES00&activeTab=summary`,
  "postcode": `EH3 9AL`,
  "address": `BF2 31 Bread Street Edinburgh EH3 9AL`,
  "reference": `23/04951/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.945972`,
  "longitude": `-3.204364`,
  },
  
  {
  "title": `Retrospective change of use of flat to short term let (sui generis) for 52 weeks in a calendar year.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0V6EWKD300&activeTab=summary`,
  "postcode": `EH2 3ES`,
  "address": `Flat 4 79 George Street New Town Edinburgh EH2 3ES`,
  "reference": `23/04934/FULSTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.953042`,
  "longitude": `-3.201221`,
  },
  
  {
  "title": `To continue operating as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L108EWKGT00&activeTab=summary`,
  "postcode": `EH1 2PW`,
  "address": `1F1 11 Johnston Terrace Edinburgh EH1 2PW`,
  "reference": `23/04975/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Wed 18 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.948508`,
  "longitude": `-3.194914`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place within the last 10 years).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L10KEWKH200&activeTab=summary`,
  "postcode": `EH3 5AJ`,
  "address": `2F2 16 St Stephen Place Edinburgh EH3 5AJ`,
  "reference": `23/04978/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.958112`,
  "longitude": `-3.207079`,
  },
  
  {
  "title": `We seek approval for the property as a lawful use for operating as short term lets, a use also known as self-catering accommodation and airbnb.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0XXEWKEY00&activeTab=summary`,
  "postcode": `EH9 1NH`,
  "address": `PF3 5 Sciennes Edinburgh EH9 1NH`,
  "reference": `23/04953/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.939332`,
  "longitude": `-3.182961`,
  },
  
  {
  "title": `To continue operating as a Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1L0X1EWKEJ00&activeTab=summary`,
  "postcode": `EH1 1LT`,
  "address": `Flat 3 4 Infirmary Street Edinburgh EH1 1LT`,
  "reference": `23/04948/CLESTL`,
  "received": `Tue 26 Sep 2023`,
  "validated": `Tue 26 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.948084`,
  "longitude": `-3.185279`,
  },
  
  {
  "title": `Retrospective change of use to short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J67KEWJWE00&activeTab=summary`,
  "postcode": `EH12 9LU`,
  "address": `11 Craw Yard Drive Edinburgh EH12 9LU`,
  "reference": `23/04785/FULSTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Tue 17 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.932602`,
  "longitude": `-3.301831`,
  },
  
  {
  "title": `Continued use as a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6AYEWK0D00&activeTab=summary`,
  "postcode": `EH1 1PZ`,
  "address": `1F1 1 Jackson's Close 209 High Street Edinburgh EH1 1PZ`,
  "reference": `23/04824/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Thu 12 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950266`,
  "longitude": `-3.188739`,
  },
  
  {
  "title": `Short term letting.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6EBEWK4O00&activeTab=summary`,
  "postcode": `EH3 9RB`,
  "address": `Flat 10 41 Lochrin Place Edinburgh EH3 9RB`,
  "reference": `23/04875/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Tue 17 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.942195`,
  "longitude": `-3.205623`,
  },
  
  {
  "title": `Retrospective change of use of flat to short term let (sui generis) for 52 weeks in a calendar year.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JMVUEWKBF00&activeTab=summary`,
  "postcode": `EH2 3ES`,
  "address": `Flat 2 79 George Street New Town Edinburgh EH2 3ES`,
  "reference": `23/04931/FULSTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.953042`,
  "longitude": `-3.201221`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JG00EWK9B00&activeTab=summary`,
  "postcode": `EH3 7RN`,
  "address": `Flat 8 20 Drumsheugh Gardens New Town Edinburgh EH3 7RN`,
  "reference": `23/04915/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.951325`,
  "longitude": `-3.214235`,
  },
  
  {
  "title": `Short term let of the property.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JFZ8EWK8O00&activeTab=summary`,
  "postcode": `EH1 2PB`,
  "address": `Flat 1 3 James' Court 493 Lawnmarket Edinburgh EH1 2PB`,
  "reference": `23/04908/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.949401`,
  "longitude": `-3.194062`,
  },
  
  {
  "title": `Retrospective change of use of flat to short term let (sui generis) for 52 weeks in a calendar year.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JMVKEWKB100&activeTab=summary`,
  "postcode": `EH2 3ES`,
  "address": `Flat 1 79 George Street Edinburgh EH2 3ES`,
  "reference": `23/04927/FULSTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.953042`,
  "longitude": `-3.201221`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place with the last 10 years but it is not material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6APEWK0000&activeTab=summary`,
  "postcode": `EH3 5EW`,
  "address": `Flat 3 17 Eyre Place Edinburgh EH3 5EW`,
  "reference": `23/04821/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.961242`,
  "longitude": `-3.199392`,
  },
  
  {
  "title": `The premises is used as a short term let and has 1 bedroom with a maximum capacity of 2 persons.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6AEEWJZK00&activeTab=summary`,
  "postcode": `EH4 3BU`,
  "address": `4 Sunbury Street New Town Edinburgh EH4 3BU`,
  "reference": `23/04817/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Fri 13 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.952226`,
  "longitude": `-3.220717`,
  },
  
  {
  "title": `The proposal is to change the use of former farm worker's cottages to short term let accommodation.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6BHEWK1700&activeTab=summary`,
  "postcode": `EH17 8RX`,
  "address": `145 Drum Street Hyvots Bank Edinburgh EH17 8RX`,
  "reference": `23/04834/FULSTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.906969`,
  "longitude": `-3.119238`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place with the last 10 years but it is not material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6EQEWK5B00&activeTab=summary`,
  "postcode": `EH6 8RF`,
  "address": `PF3 42 Buchanan Street Leith Edinburgh EH6 8RF`,
  "reference": `23/04882/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.96445`,
  "longitude": `-3.175124`,
  },
  
  {
  "title": `Short term let apartment.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6DVEWK4300&activeTab=summary`,
  "postcode": `EH3 6EN`,
  "address": `2F2 21 Heriot Row New Town Edinburgh EH3 6EN`,
  "reference": `23/04868/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.955449`,
  "longitude": `-3.2028`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place within the last 10 years but is not material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JFZUEWK9500&activeTab=summary`,
  "postcode": `EH1 2QE`,
  "address": `Flat 1 52 Candlemaker Row Old Town Edinburgh EH1 2QE`,
  "reference": `23/04913/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.947127`,
  "longitude": `-3.191861`,
  },
  
  {
  "title": `Flat has been used as a short term let since February 2022.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6BVEWK1S00&activeTab=summary`,
  "postcode": `EH1 1QQ`,
  "address": `Flat 5 1 New Assembly Close 142 High Street Edinburgh EH1 1QQ`,
  "reference": `23/04841/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 16 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.94979`,
  "longitude": `-3.188708`,
  },
  
  {
  "title": `Application for a Certificate of Lawfulness for a short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6B7EWK0P00&activeTab=summary`,
  "postcode": `EH3 6SA`,
  "address": `GF1 12 Cumberland Street Stockbridge Edinburgh EH3 6SA`,
  "reference": `23/04828/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Fri 13 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.959023`,
  "longitude": `-3.198426`,
  },
  
  {
  "title": `Short term let application for exiting short term let property.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6ELEWK5500&activeTab=summary`,
  "postcode": `EH1 1PE`,
  "address": `Flat 8 219 High Street Edinburgh EH1 1PE`,
  "reference": `23/04880/FULSTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.950169`,
  "longitude": `-3.189026`,
  },
  
  {
  "title": `Short Term Let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JMVNEWKB400&activeTab=summary`,
  "postcode": `EH3 7TD`,
  "address": `26 Randolph Lane New Town Edinburgh EH3 7TD`,
  "reference": `23/04928/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.952153`,
  "longitude": `-3.209969`,
  },
  
  {
  "title": `Change of use from residential to short term lets as been operating as STL since 2007.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JMUPEWKAB00&activeTab=summary`,
  "postcode": `EH11 2DA`,
  "address": `Flat 4 17 Caledonian Road Dalry Edinburgh EH11 2DA`,
  "reference": `23/04919/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 16 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.943977`,
  "longitude": `-3.217127`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JFXDEWK7D00&activeTab=summary`,
  "postcode": `EH4 3BY`,
  "address": `Flat 11 1 Sunbury Place New Town Edinburgh EH4 3BY`,
  "reference": `23/04895/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.951813`,
  "longitude": `-3.221633`,
  },
  
  {
  "title": `Short term let (change of use to short term let took place within the last 10 years but is not material change of use).`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J6FCEWK6500&activeTab=summary`,
  "postcode": `EH8 8HX`,
  "address": `Flat 2 80 Spring Gardens Abbeyhill Edinburgh EH8 8HX`,
  "reference": `23/04892/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.954905`,
  "longitude": `-3.164953`,
  },
  
  {
  "title": `Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1J68NEWJY100&activeTab=summary`,
  "postcode": `EH3 6DN`,
  "address": `2A Wemyss Place Mews Edinburgh EH3 6DN`,
  "reference": `23/04803/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Wed 11 Oct 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.954061`,
  "longitude": `-3.206377`,
  },
  
  {
  "title": `Short term let.`,
  "link": `https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=S1JMVSEWKBC00&activeTab=summary`,
  "postcode": `EH7 5HA`,
  "address": `11 West Montgomery Place Hillside Edinburgh EH7 5HA`,
  "reference": `23/04930/CLESTL`,
  "received": `Mon 25 Sep 2023`,
  "validated": `Mon 25 Sep 2023`,
  "status": `Awaiting Assessment`,
  "latitude": `55.960025`,
  "longitude": `-3.178354`,
  }
  
  
  ]