export const EDINBURGH_TEMPLATE = `Our city is in the midst of a catastrophic housing crisis, and I believe that every holiday let is one less home for ordinary residents to live in. This development would exacerbate the crisis for all residents of the city, displacing people from their communities, driving up rents, and further reducing the desperately needed numbers of homes in the city. Planning decisions should first and foremost cater for the needs and interests of the city’s residents, and this proposed development runs counter to that.

Moreover, I believe that this development is incompatible with planning and development policies at both a local and national level.

The Edinburgh City Plan 2030 states that “[p]roposals which would result in the loss of residential dwellings through demolition or a change of use will not be permitted”. Every proposed holiday let could be a residential dwelling, and I do not believe that granting this application is in keeping with the policies outlined in the City Plan.

The plan goes on to state that “[d]evelopments, including change of use which would have a materially detrimental effect on the living conditions of nearby residents, will not be permitted.” The impact of high concentrations of holiday lets on nearby rent levels is well documented, and I believe that granting this application will exacerbate the hardship faced by tenants in the community, and therefore is not in keeping with the City Plan.

The Scottish Government's National Planning Framework 4 states:
“Development proposals for the reuse of existing buildings for short term holiday letting should not be supported if it would result in:
• an unacceptable impact on the local amenity or character of a neighbourhood or area; or
• the loss of residential accommodation where such loss is not outweighed by local economic benefits.”

I strongly maintain that this development would have detrimental effects on the local amenity and character of the area, by removing what should be residential accommodation from local supply. I see no evidence that any local economic benefits outweigh this loss. It also seems clear to me that this development will place a significant burden on local services such as rubbish collection and public transport, negatively impacting all local residents within the community.`;



export const HIGHLANDS_TEMPLATE = `The Highlands is in the midst of a catastrophic housing crisis, and I believe that every holiday let is one less home for ordinary residents to live in. This development is exacerbating the crisis for all residents of the Highlands, displacing people from their communities, driving up rents, and is further reducing the desperately needed numbers of homes in the area. Planning decisions should first and foremost cater for the needs and interests of the area’s residents, and this proposed development runs counter to that.

In addition, the rise in short term holiday lets reduces housing availability in many Gaelic speaking areas, with disproportionate impacts on Gaelic-speaking communities. This is a key driver of community displacement, and the reason why young native Gaelic speakers need to leave the area, or are unable to return to where they grew up. This means that native Gaelic speakers are unable to afford to live in Gaelic speaking communities, preventing intergenerational language transmission, and eroding the social foundations needed to ensure the survival of the language.  The Scottish Languages Act 2025, Bòrd na Gàidhlig and public authorities establish “areas of linguistic significance,” requiring public bodies to take active measures to promote and protect Gaelic within these communities.  The growth of short term lets, reducing the ability of local communities to afford housing in their home communities is therefore in opposition to the Scottish Government's policies which aim to support the Gaelic language.

Moreover, I believe that this development is incompatible with planning and development policies at both a local and national level. The Highland-wide Local Development Plan (HwLDP), (2012), Policy 44, Tourist Accommodation, states that “proposals for tourist accommodation [must be] accommodated without adverse impacts upon neighbouring uses, compl[y] and not prejudice the residential housing land supply.” Every proposed holiday let could be a residential dwelling, and as such prejudices the availability of permanent housing for residents, and I do not believe that granting this application is in keeping with the policies outlined in the Highland-wide Local Development Plan.The plan goes on to state that developments are assessed on the extent to which they “impact on individual and community residential amenity”, and that “all developments should enhance the viability of Highland communities”. Any “developments which are judged to be significantly detrimental in terms of the above criteria will not accord with this Local Development Plan.”

High concentrations of holiday lets in the Scottish Highlands are well documented as reducing the supply of long‑term rented homes in hotspot communities, contributing to local rent and house price pressures and threatening community sustainability.

Granting this application will exacerbate the hardship faced by tenants in the community, be detrimental to individual and community residential amenity, reduce the viability of Highland communities, and therefore is not in keeping with the Highland-wide Local Development Plan (HwLDP).

In the Highland Council Local Housing Strategy (2023-2028) LHS Priority 3), it states that “people in Highland are unable to afford rural living with housing options limited due to the increase in short-term letting. Measures to consider short term let controls should be pursued.”

The Scottish Government's National Planning Framework 4 (NPF4) states that “development proposals for the reuse of existing buildings for short term holiday letting should not be supported if it would result in a) an unacceptable impact on the local amenity or character of a neighbourhood or area; or b) the loss of residential accommodation where such loss is not outweighed by local economic benefits.”

I strongly maintain that this development would have detrimental effects on the local amenity and character of the area, by removing what should be residential accommodation from local supply. I see no evidence that any local economic benefits outweigh this loss. It also seems clear to me that this development will place a significant burden on local services such as rubbish collection and public transport, negatively impacting all local residents within the community.

For all of these reasons, I urge that this application be refused in order to protect the sustainability, affordability, and long-term wellbeing of the residents of the Highlands.`;


export const BADENOCH_STRATHSPEY_TEMPLATE = `Badenoch and Strathspey is in the midst of a catastrophic housing crisis, and I believe that every holiday let is one less home for ordinary residents to live in. This development would exacerbate the crisis for all residents of the area, displacing people from their communities, driving up rents, and further reducing the desperately needed numbers of homes in the city. Planning decisions should first and foremost cater for the needs and interests of the area’s residents, and this proposed development runs counter to that.

Badenoch And Strathspey was designated as a Short Term Let Control Area in March 2024. The Statement of Reasons for this states that due to “the success of websites such as Airbnb and booking.com [there] has resulted in a big rise of houses and flats being used for temporary holiday accommodation across the United Kingdom and much of the world.” It further states that 
“the number of houses and flats being lost to this sector in Badenoch and Strathspey is such that it is unduly restricting house supply for full time residents and increasing local house prices, all to the detriment of [our] local communities.”

It highlights that “local people struggle to be able to access or afford to buy or rent housing in their local area, [and that] businesses are struggling to attract staff due to the limited availability of housing to let or buy.” Every proposed holiday let could be a residential dwelling, and I believe that granting this application perpetuates the issues listed in the Council’s own Statement of Reasons; restricted housing supply, rising local house prices, and limited housing for staff for local businesses. 

Moreover, I believe that this development is incompatible with planning and development policies at both a local and national level. The Highland-wide Local Development Plan (HwLDP, 2012), Policy 44 (Tourist Accommodation), states that “proposals for tourist accommodation [must be] accommodated without adverse impacts upon neighbouring uses, comply and not prejudice the residential housing land supply.” Every proposed holiday let reduces the availability of permanent homes for local residents, and this development cannot be considered in keeping with the aims of that policy. The HwLDP also emphasises that all developments should “enhance the viability of Highland communities,” and that those deemed detrimental in this regard “will not accord with this Local Development Plan.” It is evident that further erosion of the area’s permanent housing stock through conversion to holiday accommodation damages community viability and directly conflicts with the Local Development Plan.

The Highland Council Local Housing Strategy (2023–2028) also highlights short-term letting as a major challenge. Under LHS Priority 3 it states that “people in Highland are unable to afford rural living with housing options limited due to the increase in short-term letting. Measures to consider short term let controls should be pursued.” Allowing further conversions into holiday lets contradicts this priority and undermines the intent of Highland Council’s own housing strategy.

At the national policy level, the Scottish Government’s National Planning Framework 4 (NPF4) is equally clear. It states that “development proposals for the reuse of existing buildings for short term holiday letting should not be supported if it would result in (a) an unacceptable impact on the local amenity or character of a neighbourhood or area; or (b) the loss of residential accommodation where such loss is not outweighed by local economic benefits.” It is clear that this development would have a detrimental effect on both local amenity and neighbourhood character by removing homes from the residential supply, without evidence of any significant local economic benefit that would outweigh this harm.

High concentrations of holiday lets in Badenoch and Strathspey—and across the wider Highlands—are well documented as reducing the supply of long‑term rented homes in community “hotspots,” driving up rents and house prices, and threatening the sustainability of local communities. Granting this application would further exacerbate the hardship faced by tenants, reduce the viability of local communities, and add pressure to already stretched local services such as waste collection and public transport.

For all of these reasons, I urge that this application be refused in order to protect the sustainability, affordability, and long-term wellbeing of the Badenoch and Strathspey community.`


export const ISLANDS_TEMPLATE = `The Western Isles are in the midst of a housing crisis, and I believe that every holiday let is one less home for ordinary residents to live in.  The Scottish Government’s Island Communities Impact Assessment for rented sector reform explicitly states that “In the Western Isles, short-term lets and second homes are contributing to a shortage of housing and limiting options for people who want to remain in or move to the islands”. Young islanders “face leaving their home islands because they cannot find secure, affordable housing, with the growth of holiday lets and second homes cited as a key factor reducing the supply of homes for permanent residents”, with the lack of homes being described as a ‘threat to way of life on Western Isles’.   Working age residents and families are forced to move away, while increasing numbers of properties are used as holiday accommodation rather than permanent homes.

The Scottish Government states that ‘high concentrations of short term lets can reduce the availability of residential housing’, resulting in ‘people being unable to take up jobs in Skye and the Western Isles because there is nowhere affordable to live’. These realities are already being felt across the islands, where demand for accommodation from local people and essential workers continues to outstrip supply.

This development would exacerbate the crisis for all residents of the area, displacing people from their communities, driving up rents, and further reducing the desperately needed numbers of homes on the islands. Planning decisions should first and foremost cater for the needs and interests of the islands’ residents, and this proposed development runs counter to that principle.

Moreover, I believe that this proposal is incompatible with planning and development policies at both the local and national levels. Under the Outer Hebrides Local Development Plan (2018), Policy DP3 (Housing) seeks to “support the growth of sustainable communities across the Outer Hebrides by ensuring an adequate and effective housing land supply,” while Policy DS1 (Development Strategy) emphasises sustaining population levels and encouraging development that supports local need. The loss of residential accommodation to short-term letting directly undermines these objectives by restricting access to permanent housing and accelerating depopulation pressures in fragile communities.

Policy ED4 (Tourism) also notes that tourism uses should not have an adverse impact on the character or amenity of the area or lead to the loss of housing land needed for local residents. The conversion or use of existing housing stock for short-term holiday lets reduces the availability of homes for people wishing to live and work on the islands, directly conflicting with both the wording and spirit of this policy.

At the national policy level, the Scottish Government’s National Planning Framework 4 (NPF4) reiterates this commitment by stating that “development proposals for the reuse of existing buildings for short-term holiday letting should not be supported if it would result in (a) an unacceptable impact on the local amenity or character of a neighbourhood or area; or (b) the loss of residential accommodation where such loss is not outweighed by local economic benefits.” It is clear that this development would have a detrimental effect on the local amenity and long-term sustainability of the Western Isles by removing existing or potential residential homes from the housing market, without compelling evidence of any overriding local economic benefit.

The Western Isles face some of Scotland’s most acute population and housing challenges, with young people leaving, employers struggling to recruit, and local services becoming harder to sustain. Every additional property diverted into short-term or holiday use intensifies those issues. Granting this application would further erode the islands’ housing stock, deepen inequalities in access to housing, and undermine the resilience of island communities.

For all of these reasons, I urge that this application be refused in order to protect the sustainability, affordability, and long-term wellbeing of communities across the Western Isles.`