
  export const PlanningApps = [
  {
    "address": "Flat 1 21B Abercromby Place Edinburgh EH3 6QE",
    "postcode": "EH3 6QE",
    "received": "Received: Fri 24 Jan 2025",
    "validated": "Validated: Fri 24 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.956548",
    "longitude": "-3.197358",
    "reference": "Ref. No: 25/00365/FULSTL",
    "title": "Application is to confirm change of use from residential to short term let for an existing and established short term let business operating since 2018."
  },
  {
    "address": "4 Hope Street Edinburgh EH2 4DB",
    "postcode": "EH2 4DB",
    "received": "Received: Thu 23 Jan 2025",
    "validated": "Validated: Thu 23 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950643",
    "longitude": "-3.208593",
    "reference": "Ref. No: 25/00361/FULSTL",
    "title": "Alterations and change of use from offices to 7 short term let flats."
  },
  {
    "address": "78B Queen Street Edinburgh EH2 4NF",
    "postcode": "EH2 4NF",
    "received": "Received: Mon 20 Jan 2025",
    "validated": "Validated: Fri 24 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953244",
    "longitude": "-3.206768",
    "reference": "Ref. No: 25/00294/FULSTL",
    "title": "Retrospective change of use from residential to short term let (sui generis)."
  },
  {
    "address": "/1, 7A James' Court 493 Lawnmarket Edinburgh EH1 2PB",
    "postcode": "EH1 2PB",
    "received": "Received: Mon 13 Jan 2025",
    "validated": "Validated: Mon 13 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949401",
    "longitude": "-3.194062",
    "reference": "Ref. No: 25/00123/CLESTL",
    "title": "Property in use as short term let for over 10 years."
  },
  {
    "address": "41 London Street Edinburgh EH3 6LX",
    "postcode": "EH3 6LX",
    "received": "Received: Mon 13 Jan 2025",
    "validated": "Validated: Mon 13 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.959016",
    "longitude": "-3.191187",
    "reference": "Ref. No: 25/00127/FULSTL",
    "title": "Proposed change of use of former licenced sauna (Sui Generis) to short term let (Sui Generis)."
  },
  {
    "address": "6 Gilmerton Dykes Gardens Edinburgh EH17 8JL",
    "postcode": "EH17 8JL",
    "received": "Received: Wed 08 Jan 2025",
    "validated": "Validated: Fri 17 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.905842",
    "longitude": "-3.146974",
    "reference": "Ref. No: 25/00051/FULSTL",
    "title": "Short term let, secondary letting."
  },
  {
    "address": "2F4 9 Home Street Edinburgh EH3 9JR",
    "postcode": "EH3 9JR",
    "received": "Received: Mon 06 Jan 2025",
    "validated": "Validated: Wed 22 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.943196",
    "longitude": "-3.203365",
    "reference": "Ref. No: 25/00020/FULSTL",
    "title": "Change of use to short term let (sui generis)."
  },
  {
    "address": "1F2 8 North Bank Street Edinburgh EH1 2LP",
    "postcode": "EH1 2LP",
    "received": "Received: Tue 24 Dec 2024",
    "validated": "Validated: Fri 03 Jan 2025",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.949815",
    "longitude": "-3.193995",
    "reference": "Ref. No: 24/06321/CLESTL",
    "title": "Existing use of property for short term let accommodation."
  },
  {
    "address": "140 Braid Road Edinburgh EH10 6JB",
    "postcode": "EH10 6JB",
    "received": "Received: Wed 18 Dec 2024",
    "validated": "Validated: Mon 23 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.916427",
    "longitude": "-3.211751",
    "reference": "Ref. No: 24/06225/FULSTL",
    "title": "Proposed change of use from single occupancy domestic dwelling, to single occupancy short term let. First floor flat property with private access, and access to shared garden area."
  },
  {
    "address": "412 Webster's Land Edinburgh EH1 2RX",
    "postcode": "EH1 2RX",
    "received": "Received: Wed 11 Dec 2024",
    "validated": "Validated: Wed 11 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.946589",
    "longitude": "-3.199548",
    "reference": "Ref. No: 24/06111/CLESTL",
    "title": "Existing use of property for short term let accommodation."
  },
  {
    "address": "Flat 2 50 North Castle Street New Town Edinburgh EH2 3LU",
    "postcode": "EH2 3LU",
    "received": "Received: Tue 03 Dec 2024",
    "validated": "Validated: Tue 03 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953451",
    "longitude": "-3.204485",
    "reference": "Ref. No: 24/05905/CLESTL",
    "title": "Continued use as a Short Term Let."
  },
  {
    "address": "2F3 15 St Mary's Street Old Town Edinburgh EH1 1TA",
    "postcode": "EH1 1TA",
    "received": "Received: Tue 03 Dec 2024",
    "validated": "Validated: Tue 03 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.950309",
    "longitude": "-3.184224",
    "reference": "Ref. No: 24/05930/CLESTL",
    "title": "To continue operating as a short term let."
  },
  {
    "address": "2 Dean Path Dean Edinburgh EH4 3BA",
    "postcode": "EH4 3BA",
    "received": "Received: Tue 03 Dec 2024",
    "validated": "Validated: Tue 03 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.952648",
    "longitude": "-3.217143",
    "reference": "Ref. No: 24/05928/FULSTL",
    "title": "Extension and change of use from office to short term let (sui generis)."
  },
  {
    "address": "2F 2 Albyn Place Edinburgh EH2 4NG",
    "postcode": "EH2 4NG",
    "received": "Received: Mon 02 Dec 2024",
    "validated": "Validated: Mon 23 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953789",
    "longitude": "-3.206224",
    "reference": "Ref. No: 24/05898/FULSTL",
    "title": "Application is to confirm change of use from residential to short term let for an existing and established short term let business operating since 2018 and currently legally licenced to operate as a short term let under Licence Number EH-69520-F."
  },
  {
    "address": "1F10 2 Commercial Street North Leith Edinburgh EH6 6JA",
    "postcode": "EH6 6JA",
    "received": "Received: Mon 02 Dec 2024",
    "validated": "Validated: Mon 02 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.976387",
    "longitude": "-3.171178",
    "reference": "Ref. No: 24/05895/LBC",
    "title": "Alterations for change of use from office to serviced short term let apartments within units 1F10 and 1F20."
  },
  {
    "address": "32 Redhall Road Kingsknowe Edinburgh EH14 2HN",
    "postcode": "EH14 2HN",
    "received": "Received: Mon 25 Nov 2024",
    "validated": "Validated: Mon 02 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.923014",
    "longitude": "-3.257373",
    "reference": "Ref. No: 24/05763/CLPSTL",
    "title": "Change of use from residential to a short term let from 1st to 14th August and 24th to 31st December."
  },
  {
    "address": "3F1 113 Broughton Street Broughton Edinburgh EH1 3RZ",
    "postcode": "EH1 3RZ",
    "received": "Received: Fri 22 Nov 2024",
    "validated": "Validated: Fri 22 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.9588",
    "longitude": "-3.18993",
    "reference": "Ref. No: 24/05746/CLESTL",
    "title": "Use as short term let."
  },
  {
    "address": "7 Lindean Place Lochend Edinburgh EH6 8AY",
    "postcode": "EH6 8AY",
    "received": "Received: Fri 22 Nov 2024",
    "validated": "Validated: Fri 22 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.969053",
    "longitude": "-3.160636",
    "reference": "Ref. No: 24/05732/CLESTL",
    "title": "Short term let (STL),"
  },
  {
    "address": "1F2 45 Frederick Street New Town Edinburgh EH2 1EP",
    "postcode": "EH2 1EP",
    "received": "Received: Wed 20 Nov 2024",
    "validated": "Validated: Wed 20 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953402",
    "longitude": "-3.200271",
    "reference": "Ref. No: 24/05687/LBC",
    "title": "Proposed internal alterations to form short term let accommodation."
  },
  {
    "address": "1F2 45 Frederick Street New Town Edinburgh EH2 1EP",
    "postcode": "EH2 1EP",
    "received": "Received: Wed 20 Nov 2024",
    "validated": "Validated: Thu 21 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.953402",
    "longitude": "-3.200271",
    "reference": "Ref. No: 24/05686/FULSTL",
    "title": "Proposed change of use from offices to short term let accommodation."
  },
  {
    "address": "55 Atholl Crescent Lane Edinburgh EH3 8ET",
    "postcode": "EH3 8ET",
    "received": "Received: Mon 18 Nov 2024",
    "validated": "Validated: Wed 20 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.947864",
    "longitude": "-3.211148",
    "reference": "Ref. No: 24/05619/CLESTL",
    "title": "Property is operating as a short term let."
  },
  {
    "address": "Flat 27 50 North Bridge Edinburgh EH1 1QN",
    "postcode": "EH1 1QN",
    "received": "Received: Fri 15 Nov 2024",
    "validated": "Validated: Mon 18 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.95047",
    "longitude": "-3.188057",
    "reference": "Ref. No: 24/05603/CLESTL",
    "title": "Short term let."
  },
  {
    "address": "Flat 9 41 Lochrin Place Tollcross Edinburgh EH3 9RB",
    "postcode": "EH3 9RB",
    "received": "Received: Wed 13 Nov 2024",
    "validated": "Validated: Thu 05 Dec 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942195",
    "longitude": "-3.205623",
    "reference": "Ref. No: 24/05558/CLESTL",
    "title": "Short term letting."
  },
  {
    "address": "Flat 4 31 Lochrin Place Tollcross Edinburgh EH3 9RB",
    "postcode": "EH3 9RB",
    "received": "Received: Mon 11 Nov 2024",
    "validated": "Validated: Wed 20 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942195",
    "longitude": "-3.205623",
    "reference": "Ref. No: 24/05523/CLESTL",
    "title": "Short term letting."
  },
  {
    "address": "Flat 4 41 Lochrin Place Tollcross Edinburgh EH3 9RB",
    "postcode": "EH3 9RB",
    "received": "Received: Thu 07 Nov 2024",
    "validated": "Validated: Mon 11 Nov 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942195",
    "longitude": "-3.205623",
    "reference": "Ref. No: 24/05467/CLESTL",
    "title": "Short term letting."
  },
  {
    "address": "Flat 10 41 Lochrin Place Tollcross Edinburgh EH3 9RB",
    "postcode": "EH3 9RB",
    "received": "Received: Fri 18 Oct 2024",
    "validated": "Validated: Fri 18 Oct 2024",
    "status": "Status: Awaiting Assessment",
    "latitude": "55.942195",
    "longitude": "-3.205623",
    "reference": "Ref. No: 24/05141/CLESTL",
    "title": "Short term letting."
  }
];
  