
  export const PlanningApps = [
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use).",
    "address": "PF3 42 Buchanan Street Leith Edinburgh EH6 8RF",
    "postcode": "EH6 8RF",
    "refNo": "Ref. No: 24/04346/CLESTL",
    "received": "Received: Mon 09 Sep 2024",
    "validated": "Validated: Mon 09 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.96445",
    "lon": "-3.175124",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJJBJREWL0M00&activeTab=summary"
  },
  {
    "proposal": "Application for the issue of a certificate of lawfulness confirming that the timescale for planning enforcement in respect of the short term lettings use has expired.",
    "address": "Flat 1 2 Tytler Gardens Abbeyhill Edinburgh EH8 8HQ",
    "postcode": "EH8 8HQ",
    "refNo": "Ref. No: 24/04308/CLESTL",
    "received": "Received: Thu 05 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.954672",
    "lon": "-3.169591",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJC6O5EWKPH00&activeTab=summary"
  },
  {
    "proposal": "Application for the issue of a certificate of lawfulness confirming that the timescale for planning enforcement in respect of the short term lettings use has expired (10 years).",
    "address": "2F2 3 Bailie Fyfe's Close 107 High Street Edinburgh EH1 1SW",
    "postcode": "EH1 1SW",
    "refNo": "Ref. No: 24/04312/CLESTL",
    "received": "Received: Thu 05 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.950586",
    "lon": "-3.186331",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJCDJTEWKQI00&activeTab=summary"
  },
  {
    "proposal": "Property is in existing use as a short term let.",
    "address": "1F 15 James' Court 493 Lawnmarket Edinburgh EH1 2PB",
    "postcode": "EH1 2PB",
    "refNo": "Ref. No: 24/04315/CLESTL",
    "received": "Received: Thu 05 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.949401",
    "lon": "-3.194062",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJCDKAEWKQT00&activeTab=summary"
  },
  {
    "proposal": "Change of use to short term Let for 6 weeks in a calendar year from 01 August until 14 September.",
    "address": "Flat 1 15 Coltbridge Millside Murrayfield Edinburgh EH12 6AP",
    "postcode": "EH12 6AP",
    "refNo": "Ref. No: 24/04314/FULSTL",
    "received": "Received: Thu 05 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.946935",
    "lon": "-3.234161",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJCDK5EWKQQ00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short-term let took place within the last 10 years but is not a material change of use).",
    "address": "1F4 30 Balfour Street Pilrig Edinburgh EH6 5EP",
    "postcode": "EH6 5EP",
    "refNo": "Ref. No: 24/04263/CLESTL",
    "received": "Received: Wed 04 Sep 2024",
    "validated": "Validated: Wed 04 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.96674",
    "lon": "-3.177084",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJA27NEWKEX00&activeTab=summary"
  },
  {
    "proposal": "Currently operating a short term let.",
    "address": "1F2 76 Grassmarket Old Town Edinburgh EH1 2JR",
    "postcode": "EH1 2JR",
    "refNo": "Ref. No: 24/04288/CLESTL",
    "received": "Received: Wed 04 Sep 2024",
    "validated": "Validated: Wed 04 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.947832",
    "lon": "-3.195535",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJAIW7EWKJU00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use).",
    "address": "2F2 186 Rose Street New Town Edinburgh EH2 4BA",
    "postcode": "EH2 4BA",
    "refNo": "Ref. No: 24/04289/CLESTL",
    "received": "Received: Wed 04 Sep 2024",
    "validated": "Validated: Wed 04 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.951426",
    "lon": "-3.204341",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJAIWEEWKJX00&activeTab=summary"
  },
  {
    "proposal": "Flat has been operated for years as a short term let.",
    "address": "Flat 1 7 Western Harbour View Newhaven Edinburgh EH6 6PF",
    "postcode": "EH6 6PF",
    "refNo": "Ref. No: 24/04282/CLESTL",
    "received": "Received: Wed 04 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.987054",
    "lon": "-3.188521",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJAIVCEWKJC00&activeTab=summary"
  },
  {
    "proposal": "Respect of the short term lettings use had expired (10 years)s confirming that the timescale for planning enforcement",
    "address": "4F2 10 South College Street Old Town Edinburgh EH8 9AA",
    "postcode": "EH8 9AA",
    "refNo": "Ref. No: 24/04215/CLESTL",
    "received": "Received: Tue 03 Sep 2024",
    "validated": "Validated: Tue 03 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.946971",
    "lon": "-3.18662",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJ87ITEWK5C00&activeTab=summary"
  },
  {
    "proposal": "Short term let.",
    "address": "18B Royal Circus Edinburgh EH3 6SS",
    "postcode": "EH3 6SS",
    "refNo": "Ref. No: 24/04249/CLESTL",
    "received": "Received: Tue 03 Sep 2024",
    "validated": "Validated: Thu 05 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.957572",
    "lon": "-3.205333",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJ8O7AEWKAU00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use).",
    "address": "2F2 16 St Stephen Place Stockbridge Edinburgh EH3 5AJ",
    "postcode": "EH3 5AJ",
    "refNo": "Ref. No: 24/04251/CLESTL",
    "received": "Received: Tue 03 Sep 2024",
    "validated": "Validated: Tue 03 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.958112",
    "lon": "-3.207079",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJ8O7FEWKB000&activeTab=summary"
  },
  {
    "proposal": "Short Term Let (STL).",
    "address": "21 Scotland Street Broughton Edinburgh EH3 6PU",
    "postcode": "EH3 6PU",
    "refNo": "Ref. No: 24/04248/CLESTL",
    "received": "Received: Tue 03 Sep 2024",
    "validated": "Validated: Tue 03 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.959904",
    "lon": "-3.194673",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJ8O78EWKAR00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use). This is a resubmission of 23/04821/CLESTL.",
    "address": "Flat 3 17 Eyre Place Edinburgh EH3 5EW",
    "postcode": "EH3 5EW",
    "refNo": "Ref. No: 24/04153/CLESTL",
    "received": "Received: Fri 30 Aug 2024",
    "validated": "Validated: Fri 30 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.961242",
    "lon": "-3.199392",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SJ0SVIEWJQE00&activeTab=summary"
  },
  {
    "proposal": "Certificate of Lawfulness for flat that is being used for short term let.",
    "address": "Flat 5 4 Thorntreeside Leith Edinburgh EH6 8FF",
    "postcode": "EH6 8FF",
    "refNo": "Ref. No: 24/04031/CLESTL",
    "received": "Received: Fri 23 Aug 2024",
    "validated": "Validated: Tue 27 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.966234",
    "lon": "-3.168001",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SINU6XEWISG00&activeTab=summary"
  },
  {
    "proposal": "Change of use from a flat to short term let accommodation Sui Generis, in retrospect.",
    "address": "10A Northumberland Street South East Lane Edinburgh EH3 6LP",
    "postcode": "EH3 6LP",
    "refNo": "Ref. No: 24/04012/FULSTL",
    "received": "Received: Thu 22 Aug 2024",
    "validated": "Validated: Thu 22 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.956747",
    "lon": "-3.197284",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SILZJFEWIM600&activeTab=summary"
  },
  {
    "proposal": "Application for the issue of a Certificate of Lawfulness confirming its existing use and a short term let visitor accommodation.",
    "address": "Flat 1 8 Old Tolbooth Wynd Old Town Edinburgh EH8 8EQ",
    "postcode": "EH8 8EQ",
    "refNo": "Ref. No: 24/04024/CLESTL",
    "received": "Received: Thu 22 Aug 2024",
    "validated": "Validated: Wed 04 Sep 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952338",
    "lon": "-3.180731",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SIMG9PEWIQ600&activeTab=summary"
  },
  {
    "proposal": "Continue use as Short Term Let.",
    "address": "2 Gayfield Place Broughton Edinburgh EH7 4AB",
    "postcode": "EH7 4AB",
    "refNo": "Ref. No: 24/03973/CLESTL",
    "received": "Received: Tue 20 Aug 2024",
    "validated": "Validated: Wed 21 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.959016",
    "lon": "-3.18425",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SIIJYREWICA00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use).",
    "address": "Flat 21 41 Pilrig Heights Pilrig Edinburgh EH6 5FG",
    "postcode": "EH6 5FG",
    "refNo": "Ref. No: 24/03936/CLESTL",
    "received": "Received: Mon 19 Aug 2024",
    "validated": "Validated: Mon 19 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.966265",
    "lon": "-3.186394",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SIGFJQEWI3500&activeTab=summary"
  },
  {
    "proposal": "Proposed change of use from flat (Sui Generis) to short term let.",
    "address": "PF4 21 Duff Street Edinburgh EH11 2HJ",
    "postcode": "EH11 2HJ",
    "refNo": "Ref. No: 24/03889/FULSTL",
    "received": "Received: Thu 15 Aug 2024",
    "validated": "Validated: Thu 15 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.942827",
    "lon": "-3.22444",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SI94Z4EWHQW00&activeTab=summary"
  },
  {
    "proposal": "Short term let (change of use to short term let took place within the last 10 years but is not material change of use).",
    "address": "Flat 1 19 Caledonian Crescent Edinburgh EH11 2AL",
    "postcode": "EH11 2AL",
    "refNo": "Ref. No: 24/03907/CLESTL",
    "received": "Received: Thu 15 Aug 2024",
    "validated": "Validated: Fri 16 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.942639",
    "lon": "-3.217117",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SI9HJEEWHTT00&activeTab=summary"
  },
  {
    "proposal": "Certificate of lawfulness application for the non-material change of use to form short term let from dwelling house (flat).",
    "address": "2F3 112A West Bow Edinburgh EH1 2HH",
    "postcode": "EH1 2HH",
    "refNo": "Ref. No: 24/03818/CLESTL",
    "received": "Received: Mon 12 Aug 2024",
    "validated": "Validated: Mon 12 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.948217",
    "lon": "-3.194297",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SI3GVOEWH9500&activeTab=summary"
  },
  {
    "proposal": "Change of use from dwelling to short term let.",
    "address": "27 Glasgow Road Edinburgh EH12 8HW",
    "postcode": "EH12 8HW",
    "refNo": "Ref. No: 24/03816/FULSTL",
    "received": "Received: Mon 12 Aug 2024",
    "validated": "Validated: Mon 12 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.941983",
    "lon": "-3.296366",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SI3GVGEWH8Z00&activeTab=summary"
  },
  {
    "proposal": "The property has been in use as a short term let for the required period to demonstrate lawfulness.",
    "address": "48A North Castle Street Edinburgh EH2 3LU",
    "postcode": "EH2 3LU",
    "refNo": "Ref. No: 24/03811/CLESTL",
    "received": "Received: Mon 12 Aug 2024",
    "validated": "Validated: Mon 12 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.953451",
    "lon": "-3.204485",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SI3GV2EWH8I00&activeTab=summary"
  },
  {
    "proposal": "Change of use from residential to short term let.",
    "address": "Flat 2 80 Canongate Edinburgh EH8 8BZ",
    "postcode": "EH8 8BZ",
    "refNo": "Ref. No: 24/03782/FULSTL",
    "received": "Received: Fri 09 Aug 2024",
    "validated": "Validated: Fri 09 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952043",
    "lon": "-3.17675",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHXWV6EWH1R00&activeTab=summary"
  },
  {
    "proposal": "Change of use from residential to short term let.",
    "address": "1F 1 South Oswald Road Grange Edinburgh EH9 2HQ",
    "postcode": "EH9 2HQ",
    "refNo": "Ref. No: 24/03781/CLESTL",
    "received": "Received: Fri 09 Aug 2024",
    "validated": "Validated: Tue 13 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.928472",
    "lon": "-3.191032",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHXWV2EWH1O00&activeTab=summary"
  },
  {
    "proposal": "Planning permission sought for the change of use from residential to short term let in retrospect.",
    "address": "113 Upper Craigour Edinburgh EH17 7SE",
    "postcode": "EH17 7SE",
    "refNo": "Ref. No: 24/03764/FULSTL",
    "received": "Received: Thu 08 Aug 2024",
    "validated": "Validated: Fri 09 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.918217",
    "lon": "-3.136091",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHW27CEWGWB00&activeTab=summary"
  },
  {
    "proposal": "Application for the issue of a certificate of lawfulness confirming its existing use as short term let visitor accommodation.",
    "address": "Flat 1 1 Bethlehem Way Edinburgh EH7 6FB",
    "postcode": "EH7 6FB",
    "refNo": "Ref. No: 24/03749/CLESTL",
    "received": "Received: Wed 07 Aug 2024",
    "validated": "Validated: Wed 07 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.963846",
    "lon": "-3.16016",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHU7KMEWGQZ00&activeTab=summary"
  },
  {
    "proposal": "Retrospective change of use application for short term let as used for 8 years.",
    "address": "Flat 8 11 James' Court 493 Lawnmarket Edinburgh EH1 2PB",
    "postcode": "EH1 2PB",
    "refNo": "Ref. No: 24/03736/FULSTL",
    "received": "Received: Tue 06 Aug 2024",
    "validated": "Validated: Wed 07 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.949401",
    "lon": "-3.194062",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHSTJAEWGOB00&activeTab=summary"
  },
  {
    "proposal": "To continue use as Short Term Let.",
    "address": "Flat 2 10 Boat Green Warriston Edinburgh EH3 5LL",
    "postcode": "EH3 5LL",
    "refNo": "Ref. No: 24/03657/CLESTL",
    "received": "Received: Thu 01 Aug 2024",
    "validated": "Validated: Thu 08 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.964142",
    "lon": "-3.198632",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHJK6YEWG6700&activeTab=summary"
  },
  {
    "proposal": "Permission for short term let.",
    "address": "Flat 2 4 Davie Street Newington Edinburgh EH8 9EB",
    "postcode": "EH8 9EB",
    "refNo": "Ref. No: 24/03660/CLESTL",
    "received": "Received: Thu 01 Aug 2024",
    "validated": "Validated: Wed 21 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.945418",
    "lon": "-3.182698",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHJK75EWG6I00&activeTab=summary"
  },
  {
    "proposal": "Existing use as a short term let over 10 years.",
    "address": "PF2 16 Elgin Terrace Hillside Edinburgh EH7 5NW",
    "postcode": "EH7 5NW",
    "refNo": "Ref. No: 24/03644/CLESTL",
    "received": "Received: Thu 01 Aug 2024",
    "validated": "Validated: Tue 06 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.960292",
    "lon": "-3.172389",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHJ3J3EWG2X00&activeTab=summary"
  },
  {
    "proposal": "Change of use from residential to a short term let (in retrospect).",
    "address": "4 Eastfield Edinburgh EH15 2PW",
    "postcode": "EH15 2PW",
    "refNo": "Ref. No: 24/03634/FULSTL",
    "received": "Received: Wed 31 Jul 2024",
    "validated": "Validated: Mon 12 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.948138",
    "lon": "-3.083371",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHHPJREWFZU00&activeTab=summary"
  },
  {
    "proposal": "Change of Use (from residential to short term let).",
    "address": "Flat 7 30B Chambers Street Edinburgh EH1 1HU",
    "postcode": "EH1 1HU",
    "refNo": "Ref. No: 24/03575/FULSTL",
    "received": "Received: Mon 29 Jul 2024",
    "validated": "Validated: Tue 13 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.947406",
    "lon": "-3.190845",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHDJIUEWFK300&activeTab=summary"
  },
  {
    "proposal": "Short Term Let (STL).",
    "address": "PF2 1 Barony Place Broughton Edinburgh EH3 6PB",
    "postcode": "EH3 6PB",
    "refNo": "Ref. No: 24/03571/CLESTL",
    "received": "Received: Mon 29 Jul 2024",
    "validated": "Validated: Wed 31 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.958297",
    "lon": "-3.191213",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SHDJIKEWFJP00&activeTab=summary"
  },
  {
    "proposal": "Change of use from a residential property to a short term let.",
    "address": "11 St Stephen Place Edinburgh EH3 5AJ",
    "postcode": "EH3 5AJ",
    "refNo": "Ref. No: 24/03464/FULSTL",
    "received": "Received: Mon 22 Jul 2024",
    "validated": "Validated: Fri 09 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.958112",
    "lon": "-3.207079",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SH0KVWEWMII00&activeTab=summary"
  },
  {
    "proposal": "To continue to use as a short term let.",
    "address": "1F 10 Ainslie Place Edinburgh EH3 6AS",
    "postcode": "EH3 6AS",
    "refNo": "Ref. No: 24/03447/CLESTL",
    "received": "Received: Fri 19 Jul 2024",
    "validated": "Validated: Tue 06 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.953318",
    "lon": "-3.211158",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SGV0WDEWMC800&activeTab=summary"
  },
  {
    "proposal": "Planning permission is sought to operate the property on a short term let basis (in retrospect).",
    "address": "3F2 245 Dalkeith Road Edinburgh EH16 5JS",
    "postcode": "EH16 5JS",
    "refNo": "Ref. No: 24/03347/FULSTL",
    "received": "Received: Mon 15 Jul 2024",
    "validated": "Validated: Thu 08 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.93248",
    "lon": "-3.16468",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SGNM8FEWLPQ00&activeTab=summary"
  },
  {
    "proposal": "To continue use as a short term let.",
    "address": "2F2 4 Northumberland Place Edinburgh EH3 6LQ",
    "postcode": "EH3 6LQ",
    "refNo": "Ref. No: 24/03309/CLESTL",
    "received": "Received: Thu 11 Jul 2024",
    "validated": "Validated: Tue 30 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.957251",
    "lon": "-3.195824",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SGGHDYEWLGG00&activeTab=summary"
  },
  {
    "proposal": "Change of use from office (Class 4) to short term let accommodation (sui generis) and replacement of door on rear elevation with window.",
    "address": "GF 5 Wemyss Place Edinburgh EH3 6DH",
    "postcode": "EH3 6DH",
    "refNo": "Ref. No: 24/03274/FULSTL",
    "received": "Received: Wed 10 Jul 2024",
    "validated": "Validated: Thu 11 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.954101",
    "lon": "-3.20601",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SGECWKEWL8Q00&activeTab=summary"
  },
  {
    "proposal": "Change of use from residential dwelling with two bedrooms to short term let use with one bedroom, where the property is not a principal home under Section 26B of the Town and Country Planning (Scotland) Act 1997.",
    "address": "Flat 1 11 Fountain Close 22 High Street Edinburgh EH1 1TF",
    "postcode": "EH1 1TF",
    "refNo": "Ref. No: 24/03276/CLESTL",
    "received": "Received: Wed 10 Jul 2024",
    "validated": "Validated: Thu 01 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.950187",
    "lon": "-3.184813",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SGECWVEWL8Y00&activeTab=summary"
  },
  {
    "proposal": "Serviced accommodation /short term let which has been in operation intermittently for many years and during the fringe period.",
    "address": "34 Bridge Street Newbridge EH28 8SR",
    "postcode": "EH28 8SR",
    "refNo": "Ref. No: 24/03151/CLESTL",
    "received": "Received: Wed 03 Jul 2024",
    "validated": "Validated: Mon 19 Aug 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.939079",
    "lon": "-3.409444",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SG1E7LEWKFW00&activeTab=summary"
  },
  {
    "proposal": "Use of the Coach House Cottage as short term let accommodation.",
    "address": "Ratho Hall Baird Road Ratho Newbridge EH28 8QY",
    "postcode": "EH28 8QY",
    "refNo": "Ref. No: 24/03082/CLESTL",
    "received": "Received: Fri 28 Jun 2024",
    "validated": "Validated: Wed 10 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.924373",
    "lon": "-3.383719",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SFSEMNEWJZD00&activeTab=summary"
  },
  {
    "proposal": "Application for a certificate of lawfulness for a short term let.",
    "address": "1F2 15 Dean Bank Lane Edinburgh EH3 5BS",
    "postcode": "EH3 5BS",
    "refNo": "Ref. No: 24/03062/CLESTL",
    "received": "Received: Fri 28 Jun 2024",
    "validated": "Validated: Mon 15 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.959116",
    "lon": "-3.208216",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SFS4VHEWJWL00&activeTab=summary"
  },
  {
    "proposal": "Continue operating as a short term lets.",
    "address": "Flat 10 227 High Street Edinburgh EH1 1PE",
    "postcode": "EH1 1PE",
    "refNo": "Ref. No: 24/03012/CLESTL",
    "received": "Received: Tue 25 Jun 2024",
    "validated": "Validated: Tue 25 Jun 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.950169",
    "lon": "-3.189026",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SFMUNMEWJGP00&activeTab=summary"
  },
  {
    "proposal": "Retrospective change of use from residential to temporary short-term letting for the six-week period commencing 22nd July and ending 31st August in each year noting that the property has been used as a short term let for at least the last 8 years.",
    "address": "Flat 2 259 Canongate Edinburgh EH8 8BQ",
    "postcode": "EH8 8BQ",
    "refNo": "Ref. No: 24/02891/FULSTL",
    "received": "Received: Tue 18 Jun 2024",
    "validated": "Validated: Tue 18 Jun 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.950955",
    "lon": "-3.182916",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SFA2V6EWILS00&activeTab=summary"
  },
  {
    "proposal": "Change of use to short term let.",
    "address": "1F1 62 Thistle Street Edinburgh EH2 1EN",
    "postcode": "EH2 1EN",
    "refNo": "Ref. No: 24/02882/FULSTL",
    "received": "Received: Tue 18 Jun 2024",
    "validated": "Validated: Mon 15 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.953847",
    "lon": "-3.199387",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SF9M89EWIJ800&activeTab=summary"
  },
  {
    "proposal": "Property is a short term let used as holiday accommodation.",
    "address": "2F1 16 North St Andrew Street Edinburgh EH2 1HJ",
    "postcode": "EH2 1HJ",
    "refNo": "Ref. No: 24/02669/CLESTL",
    "received": "Received: Wed 05 Jun 2024",
    "validated": "Validated: Wed 05 Jun 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.955603",
    "lon": "-3.192458",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SELJKXEWGY200&activeTab=summary"
  },
  {
    "proposal": "Short term let for over 10 years.",
    "address": "3F1 29 Frederick Street Edinburgh EH2 2ND",
    "postcode": "EH2 2ND",
    "refNo": "Ref. No: 24/02617/CLESTL",
    "received": "Received: Mon 03 Jun 2024",
    "validated": "Validated: Wed 10 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952603",
    "lon": "-3.199813",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SEHUCEEWGJG00&activeTab=summary"
  },
  {
    "proposal": "Short term let for over 10 years.",
    "address": "2F1 29 Frederick Street Edinburgh EH2 2ND",
    "postcode": "EH2 2ND",
    "refNo": "Ref. No: 24/02616/CLESTL",
    "received": "Received: Mon 03 Jun 2024",
    "validated": "Validated: Mon 15 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952603",
    "lon": "-3.199813",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SEHUCCEWGJD00&activeTab=summary"
  },
  {
    "proposal": "Short term let for over 10 years.",
    "address": "1F1 29 Frederick Street Edinburgh EH2 2ND",
    "postcode": "EH2 2ND",
    "refNo": "Ref. No: 24/02615/CLESTL",
    "received": "Received: Mon 03 Jun 2024",
    "validated": "Validated: Wed 10 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952603",
    "lon": "-3.199813",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SEHUCAEWGJA00&activeTab=summary"
  },
  {
    "proposal": "Property is a short term let used as holiday accommodation.",
    "address": "2F1 108 Rose Street Edinburgh EH2 3JF",
    "postcode": "EH2 3JF",
    "refNo": "Ref. No: 24/02613/CLESTL",
    "received": "Received: Mon 03 Jun 2024",
    "validated": "Validated: Mon 03 Jun 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952036",
    "lon": "-3.200788",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SEHUC6EWGJ400&activeTab=summary"
  },
  {
    "proposal": "Sub-division and change of use to short term let (Sui Generis) and associated layout changes.",
    "address": "Flat 3 6 Falcon Road West Edinburgh EH10 4AQ",
    "postcode": "EH10 4AQ",
    "refNo": "Ref. No: 24/02480/FULSTL",
    "received": "Received: Fri 24 May 2024",
    "validated": "Validated: Tue 09 Jul 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.929168",
    "lon": "-3.206307",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDZS7DEWFG600&activeTab=summary"
  },
  {
    "proposal": "Internal and external alterations to facilitate conversion from office /workshop to form two short term lets and one flatted dwellinghouse.",
    "address": "6A Grange Road Edinburgh EH9 1UH",
    "postcode": "EH9 1UH",
    "refNo": "Ref. No: 24/02464/LBC",
    "received": "Received: Fri 24 May 2024",
    "validated": "Validated: Tue 28 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.936731",
    "lon": "-3.181058",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDZBJDEWN0Z00&activeTab=summary"
  },
  {
    "proposal": "Short term let.",
    "address": "32A Royal Circus Edinburgh EH3 6SS",
    "postcode": "EH3 6SS",
    "refNo": "Ref. No: 24/02468/CLESTL",
    "received": "Received: Fri 24 May 2024",
    "validated": "Validated: Fri 24 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.957572",
    "lon": "-3.205333",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDZBJMEWN1D00&activeTab=summary"
  },
  {
    "proposal": "Change of use from office /workshop premises to two short term let units and one flatted dwellinghouse.",
    "address": "6A Grange Road Edinburgh EH9 1UH",
    "postcode": "EH9 1UH",
    "refNo": "Ref. No: 24/02469/FULSTL",
    "received": "Received: Fri 24 May 2024",
    "validated": "Validated: Mon 27 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.936731",
    "lon": "-3.181058",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDZBJQEWN1I00&activeTab=summary"
  },
  {
    "proposal": "Short term let.",
    "address": "Flat 4B 13 North Bank Street Edinburgh EH1 2LP",
    "postcode": "EH1 2LP",
    "refNo": "Ref. No: 24/02453/CLESTL",
    "received": "Received: Thu 23 May 2024",
    "validated": "Validated: Thu 23 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.949815",
    "lon": "-3.193995",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDXQMHEWMY000&activeTab=summary"
  },
  {
    "proposal": "Certificate of lawfulness application for existing use as a short term let (Sui Generis).",
    "address": "Flat 2 138 Calton Road Edinburgh EH8 8DP",
    "postcode": "EH8 8DP",
    "refNo": "Ref. No: 24/02370/CLESTL",
    "received": "Received: Fri 17 May 2024",
    "validated": "Validated: Tue 21 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.952762",
    "lon": "-3.179032",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDMMLKEWM8400&activeTab=summary"
  },
  {
    "proposal": "Short term let.",
    "address": "1F1 16 Broughton Place Edinburgh EH1 3RX",
    "postcode": "EH1 3RX",
    "refNo": "Ref. No: 24/02374/CLESTL",
    "received": "Received: Fri 17 May 2024",
    "validated": "Validated: Wed 22 May 2024",
    "status": "Status: Awaiting Assessment",
    "lat": "55.958794",
    "lon": "-3.189066",
    "link": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/applicationDetails.do?keyVal=SDMMMCEWM8O00&activeTab=summary"
  }
];
  