export const Councillors = [
    {email: "robert.aldridge@edinburgh.gov.uk",
    cllr: `Councillor Robert Aldridge`, 
    ward: 'Drum Brae/Gyle'},
    {email: "Scott.Arthur@edinburgh.gov.uk",
    cllr: `Councillor Scott Arthur`, 
    ward: 'Colinton/Fairmilehead'},
    {email: "Cllr.Danny.Aston@edinburgh.gov.uk",
    cllr: `Councillor Danny Aston`, 
    ward: 'Craigentinny/Duddingston'},
    {email: "Cllr.Jule.Bandel@edinburgh.gov.uk",
    cllr: `Councillor Jule Bandel`, 
    ward: 'Inverleith'},
    {email: "Cllr.Alan.Beal@edinburgh.gov.uk",
    cllr: `Councillor Alan Beal`, 
    ward: 'Corstorphine/Murrayfield'},
    {email: "Cllr.Marco.Biagi@edinburgh.gov.uk",
    cllr: `Councillor Marco Biagi`, 
    ward: 'Colinton/Fairmilehead'},
    {email: "chas.booth@edinburgh.gov.uk",
    cllr: `Councillor Chas Booth`, 
    ward: 'Leith'},
    {email: "graeme.bruce@edinburgh.gov.uk",
    cllr: `Councillor Graeme Bruce`, 
    ward: 'Pentland Hills'},
    {email: "Steve.Burgess@edinburgh.gov.uk",
    cllr: `Councillor Steve Burgess`, 
    ward: 'Southside/Newington'},
    {email: "Cllr.Jack.Caldwell@edinburgh.gov.uk",
    cllr: `Councillor Jack Caldwell`, 
    ward: 'Leith Walk'},
    {email: "lezleymarion.cameron@edinburgh.gov.uk",
    cllr: `Councillor Lezley Marion Cameron`, 
    ward: 'Liberton/Gilmerton'},
    {email: "kate.campbell@edinburgh.gov.uk",
    cllr: `Councillor Kate Campbell`, 
    ward: 'Portobello/Craigmillar'},
    {email: "Cllr.Martha.MattosCoelho@edinburgh.gov.uk",
    cllr: `Councillor Martha Mattos Coelho`, 
    ward: 'Liberton/Gilmerton'},
    {email: "Cllr.Christopher.Cowdy@edinburgh.gov.uk",
    cllr: `Councillor Christopher Cowdy`, 
    ward: 'Fountainbridge/ Craiglockhart'},
    {email: "Cllr.James.Dalgleish@edinburgh.gov.uk",
    cllr: `Councillor James Dalgleish`, 
    ward: 'Leith Walk'},
    {email: "Cllr.Euan.Davidson@edinburgh.gov.uk",
    cllr: `Councillor Euan Davidson`, 
    ward: 'Corstorphine/Murrayfield'},
    {email: "Cammy.Day@edinburgh.gov.uk",
    cllr: `Councillor Cammy Day`, 
    ward: 'Forth'},
    {email: "Cllr.Sanne.Dijkstra-Downie@edinburgh.gov.uk",
    cllr: `Councillor Sanne Dijkstra-Downie`, 
    ward: 'Forth'},
    {email: "denis.dixon@edinburgh.gov.uk",
    cllr: `Councillor Denis Dixon`, 
    ward: 'Sighthill/Gorgie'},
    {email: "Cllr.Stuart.Dobbin@edinburgh.gov.uk",
    cllr: `Councillor Stuart Dobbin`, 
    ward: 'Forth'},
    {email: "phil.doggart@edinburgh.gov.uk",
    cllr: `Councillor Phil Doggart`, 
    ward: 'Liberton/Gilmerton'},
    {email: "Cllr.Katrina.Faccenda@edinburgh.gov.uk",
    cllr: `Councillor Katrina Faccenda`, 
    ward: 'Leith'},
    {email: "Cllr.Pauline.Flannery@edinburgh.gov.uk",
    cllr: `Councillor Pauline Flannery`, 
    ward: 'Southside/Newington'},
    {email: "cathy.fullerton@edinburgh.gov.uk",
    cllr: `Councillor Catherine Fullerton`, 
    ward: 'Sighthill/Gorgie'},
    {email: "neil.gardiner@edinburgh.gov.uk",
    cllr: `Councillor Neil Gardiner`, 
    ward: 'Pentland Hills'},
    {email: "Cllr.Fiona.Glasgow@edinburgh.gov.uk",
    cllr: `Councillor Fiona Glasgow`, 
    ward: 'Pentland Hills'},
    {email: "Cllr.Margaret.Graham@edinburgh.gov.uk",
    cllr: `Councillor Margaret Arma Graham`, 
    ward: 'City Centre'},
    {email: "joan.griffiths@edinburgh.gov.uk",
    cllr: `Councillor Joan Griffiths`, 
    ward: 'Craigentinny/Duddingston'},
    {email: "Cllr.Dan.Heap@edinburgh.gov.uk",
    cllr: `Councillor Dan Heap`, 
    ward: 'Sighthill/Gorgie'},
    {email: "Cllr.Euan.Hyslop@edinburgh.gov.uk",
    cllr: `Councillor Euan Hyslop`, 
    ward: 'Drum Brae/Gyle'},
    {email: "Cllr.Stephen.Jenkinson@edinburgh.gov.uk",
    cllr: `Councillor Stephen Jenkinson`, 
    ward: 'Pentland Hills'},
    {email: "Cllr.Tim.Jones@edinburgh.gov.uk",
    cllr: `Councillor Tim Jones`, 
    ward: 'Portobello/Craigmillar'},
    {email: "david.key@edinburgh.gov.uk",
    cllr: `Councillor David Key`, 
    ward: 'Fountainbridge/ Craiglockhart'},
    {email: "Cllr.Simita.Kumar@edinburgh.gov.uk",
    cllr: `Councillor Simita Kumar`, 
    ward: 'Southside/Newington'},
    {email: "kevin.lang@edinburgh.gov.uk",
    cllr: `Councillor Kevin Lang`, 
    ward: 'Almond'},
    {email: "lesley.macinnes@edinburgh.gov.uk",
    cllr: `Councillor Lesley Macinnes`, 
    ward: 'Liberton/Gilmerton'},
    {email: "Cllr.Marie-Clair.Munro@edinburgh.gov.uk",
    cllr: `Councillor Marie-Clair Munro`, 
    ward: 'Morningside'},
    {email: "Cllr.Finlay.Mcfarlane@edinburgh.gov.uk",
    cllr: `Councillor Finlay McFarlane`, 
    ward: 'City Centre'},
    {email: "Cllr.Ross.Mckenzie@edinburgh.gov.uk",
    cllr: `Councillor Ross McKenzie`, 
    ward: 'Sighthill/Gorgie'},
    {email: "cllr.amy.mcneese-mechan@edinburgh.gov.uk",
    cllr: `Councillor Amy McNeese-Mechan`, 
    ward: 'Leith Walk'},
    {email: "adam.mcvey@edinburgh.gov.uk",
    cllr: `Councillor Adam McVey`, 
    ward: 'Leith'},
    {email: "Cllr.Jane.Meagher@edinburgh.gov.uk",
    cllr: `Councillor Jane Meagher`, 
    ward: 'Portobello/Craigmillar'},
    {email: "C.Miller@edinburgh.gov.uk",
    cllr: `Councillor Claire Miller`, 
    ward: 'City Centre'},
    {email: "max.mitchell@edinburgh.gov.uk",
    cllr: `Councillor Max Mitchell`, 
    ward: 'Inverleith'},
    {email: "cllr.jo.mowat@edinburgh.gov.uk",
    cllr: `Councillor Joanna Mowat`, 
    ward: 'City Centre'},
    {email: "Cllr.Alys.Mumford@edinburgh.gov.uk",
    cllr: `Councillor Alys Mumford`, 
    ward: 'Portobello/Craigmillar'},
    {email: "Cllr.Vicky.Nicolson@edinburgh.gov.uk",
    cllr: `Councillor Vicky Nicolson`, 
    ward: 'Inverleith'},
    {email: "Cllr.Kayleigh.ONeill@edinburgh.gov.uk",
    cllr: `Councillor Kayleigh O'Neill`, 
    ward: 'Forth'},
    {email: "hal.osler@edinburgh.gov.uk",
    cllr: `Councillor Hal Osler`, 
    ward: 'Inverleith'},
    {email: "Cllr.Ben.Parker@edinburgh.gov.uk",
    cllr: `Councillor Ben Parker`, 
    ward: 'Morningside'},
    {email: "Cllr.Tim.Pogson@edinburgh.gov.uk",
    cllr: `Councillor Tim Pogson`, 
    ward: 'Southside/Newington'},
    {email: "susan.rae@edinburgh.gov.uk",
    cllr: `Councillor Susan Rae`, 
    ward: 'Leith Walk'},
    {email: "frank.ross@edinburgh.gov.uk",
    cllr: `Councillor Frank Ross`, 
    ward: 'Corstorphine/Murrayfield'},
    {email: "neil.ross@edinburgh.gov.uk",
    cllr: `Councillor Neil Ross`, 
    ward: 'Morningside'},
    {email: "jason.rust@edinburgh.gov.uk",
    cllr: `Councillor Jason Rust`, 
    ward: 'Colinton/Fairmilehead'},
    {email: "alex.staniforth@edinburgh.gov.uk",
    cllr: `Councillor Alex Staniforth`, 
    ward: 'Craigentinny/Duddingston'},
    {email: "Cllr.Edward.Thornley@edinburgh.gov.uk",
    cllr: `Councillor Edward Thornley`, 
    ward: 'Drum Brae/Gyle'},
    {email: "Cllr.Val.Walker@edinburgh.gov.uk",
    cllr: `Councillor Val Walker`, 
    ward: 'Fountainbridge/ Craiglockhart'},
    {email: "mandy.watt@edinburgh.gov.uk",
    cllr: `Councillor Mandy Watt`, 
    ward: 'Morningside'},
    {email: "iain.whyte@edinburgh.gov.uk",
    cllr: `Councillor Iain Whyte`, 
    ward: 'Craigentinny/Duddingston'},
    {email: "norman.work@edinburgh.gov.uk",
    cllr: `Councillor Norman Work`, 
    ward: 'Almond'},
    {email: "louise.young@edinburgh.gov.uk",
    cllr: `Councillor Louise Young`, 
    ward: 'Almond'},
    {email: "Cllr.Lewis.Younie@edinburgh.gov.uk",
    cllr: `Councillor Lewis Younie`, 
    ward: 'Almond'},
  ]
  